---

- block:
    - name: "{{ verifyFTP }} - Verify if the directory exists in server {{inventory_hostname}}" 
      win_stat:
        path: "{{ ftpdir2bVerified }}"
      register: conn_test_path

    - fail:
        msg: "{{ verifyFTP }}- directory {{ ftpdir2bVerified }} doesn't exist in server {{inventory_hostname}}!"
      when: not conn_test_path.stat.exists

    - name: "{{ verifyFTP }} - check if files exists in dir {{ ftpdir2bVerified }}"
      win_command: powershell.exe -
      args:
        stdin: cd -Path {{ftpdir2bVerified}} -PassThru ; $fileCount = (Get-ChildItem -File | Measure-Object).Count ; Write-Host "fileCount $fileCount"
      register: result
   
    - set_fact:
        fileCount: "{{ item.split()[1] }}"
      when: item | regex_search('fileCount')
      with_items: "{{result.stdout_lines}}"

    - debug:
        msg: "{{ verifyFTP }}- File(s) exists in dir {{ ftpdir2bVerified }}. Verification OK"
      when: fileCount|int > 0      

    - fail:
        msg: "{{ verifyFTP }}- Dir {{ ftpdir2bVerified }} is empty! Verification failed!"
      when: fileCount|int == 0

  tags:
    - A15
    - B17

