---
- block:

    - name: "{{actNo}} - Check if the file {{fileRenameFrom}} exist"
      win_stat: 
        path: "{{fileRenameFrom}}"
      register: fileStat

    - name: "{{actNo}} - Replace file {{fileRenameFrom}}"
      win_shell: |
        Move-Item '{{fileRenameFrom}}' '{{fileRenameTo}}'
      register: copyStat
      when: fileStat.stat.exists
    
    - debug:
        var: copyStat

    - fail:
        msg: "{{actNo}} - file {{fileRenameFrom}} does not exist. Please check!"
      when: not fileStat.stat.exists

    - debug:
        msg: "{{actNo}} - file {{fileRenameFrom}} renamed to {{fileRenameTo}}"
      when: copyStat.changed

  tags:
    - A7a
    - A7b 
