---
- block:
    - debug:
        var: latestLogFileName

    - win_stat:
        path: "{{ latestLogFileName }}"
        get_checksum: no
      register: batchLog_path
      
    - name: "{{ actNo }} - Running batch file to Start GWC Application"
      ansible.windows.win_powershell:
        script: |
          start-process -NoNewWindow .\{{ startScript }}
        chdir: "{{ dir2ChangeTo }}"
      async: 10
      ignore_errors: yes
      register: batchRun_state

    - debug:
        var: batchRun_state

    - block:
      - name: "{{ actNo }} - kill the java process"
        win_shell: Stop-Process -Name "java" -Force
        ignore_errors: yes
        register: killStatus
      when: killJavaProcess

    - name: "{{ actNo }} - Check startup script run status"
      win_shell: get-content '{{ latestLogFileName }}' -Tail '{{ log_tail_line }}'
      register: output
      until: output.stdout.find("{{ log_keyword }}") != -1
      retries: 3
      delay: 2
      ignore_errors: yes

    - assert:
        that:
          - output.stdout.find("{{ log_keyword }}") != -1
        fail_msg: "{{failMsg}}"
        success_msg: "{{successMsg}}"

  tags:
    - A8d
