---
- block:
  - name: "{{ actNo }} - Edit {{ entryToEdit }} for {{ inventory_hostname }}"
    win_regedit:
      path: "{{ entryPath }}"
      name: "(( entryToEdit }}"
      data: "{{ valueToEdit }}"
      type: "{{ entryType }}"
    register: regedit_stat

  - debug:
      msg: "{{ actNo }} - Registry key (( entryToEdit }} has been updated successfully"
    when: regedit_stat is changed and regedit_stat.data_changed
    #when: regedit_stat.changed == true and regedit_stat.data_changed == true

  - fail:
      msg: "{{ actNo }} - Something wrong while updating registry key (( entryToEdit }}. Please check"
    when: regedit_stat.failed
    #when: regedit_stat.failed == true

  tags:
    - A19.2
    - B19.2
