---
- hosts: win
  vars:
    mysrc: 'C:\Users\pdmskul\Videos\Apache Tomcat Server\Tomcat 7.1\bin\server.xml.dr'
    mydst: 'C:\Users\pdmskul\Videos\Apache Tomcat Server\Tomcat 7.1\bin\server.xml'
  tasks:
    - name: Check if file exists
      win_stat:
        path: "{{ mysrc }}"
      register: check_file_name
    - name: print debug
      debug:
        var: check_file_name
    - name: Copy file with new name
      win_copy:
        remote_src: true
        src: "{{ mysrc }}"
        dest: "{{ mydst }}"
      when: check_file_name.stat.exists
    - name: Remove old file
      win_file:
        path: "{{ mysrc }}"
        state: absent
      when: check_file_name.stat.exists