---
- block:
  - debug:
      msg: "{{ bring_down_web01_06 }}- Bring down Maintenance page on Web01-Web06"

  - stat:
      path: "{{ web_server_bring_down_maintenance_script }}"
    register: web_maintenance_down_script

  - fail:
      msg: "{{ bring_down_web01_06 }}- Web server bring down maintenance script path {{ web_server_bring_down_maintenance_script }}  doesn't exist."
    when: not web_maintenance_down_script.stat.exists

  - name: "{{ bring_down_web01_06 }}-Bring down the web01 to web06 maintenance page"
    command: "{{ web_server_bring_down_maintenance_script }}"

  - pause:
      seconds: "{{pause_duration}}"

  - name: "{{ bring_down_web01_web06 }}- URL to check is as follows"
    set_fact:
      url_2b_verify: 'https://{{inventory_hostname}}/rib'

  - name: "{{ bring_down_web01_06 }}- Verifying the url {{ url_2b_verify }}"
    uri:
      url: "{{ url_2b_verify }}"
      status_code: 500
      validate_certs: no
    register: validate_result
    ignore_errors: yes

  - name: "{{ bring_down_web01_06 }}- Web-Appserver: Report the status of maintenance page"
    debug:
      msg: "{{ bring_down_web01_06 }}- Web maintenance page verification is successful. The page is down."
    when: validate_result.status == 500

  - fail:
      msg: "{{ bring_down_web01_06 }}- Maintenance page is not brought down, or is already down but replaced by another page. Please check!"
    when: validate_result.status != 500

  become: yes
  tags:
    - B35
    - B36
    - B37
    - B38
    - B39
    - B40

