---
- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "P15-P17"
    svc_name: "TBD"
    action: "stop"
  when: inventory_hostname in app_ips
  tags: [P15-P17]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/DBMirrorCheckSyncAndMirrorRole.yml"
  vars:
    DBMirroring: "P16-P18"
    SQLServerInstance: "??"
    DBName: "master"
    checkSync: "SYNCHRONIZED"
    mirrorRole: "PRINCIPAL"
    DB2BSwitchOver: "??"
  when: inventory_hostname in db_ip
  tags: [P16-P18]

