---
#Verify if the springcloud is already stopped
- name: "Checking the status of spring cloud"
  pids:
    name: Appzillon
    #sc is acronym for springcloud
  register: sc_status

- debug:
    msg: "Spring cloud is already in stopped state"
  when: sc_status.pids|length == 0

- name: "Stopping spring cloud"
  block:
    - name: "Killing the process id {{ sc_status.pids[0] }}"
      shell:
        cmd: "kill -9 {{ sc_status.pids[0] }}"

    - name: "Verifying the status of spring cloud"
      pids:
        name: Appzillon
        #sc is acronym for springcloud
      register: sc_status_verify

    - fail:
        msg: "Not able to kill spring cloud with process id sc_status.pids[0]"
      when: not sc_status_verify.pids|length == 0

    - debug:
        msg: "Spring cloud is successfully stopped."
  when: not sc_status.pids|length == 0


