---
- block:
    - include_tasks: "{{ role_path }}/../go-no-go/tasks/bring_up_web.yml"
      vars:
        bring_up_web1_web6: "A32"
      when: inventory_hostname in dr_web_ips
      tags: [A32]
  become: yes

- include_tasks: update_hosts_CDB_server.yml
  vars:
    Update_host_CDB_Server: "A34"
    CDB_find_line: '^172\.31\.1\.119'
    CDB_line2Replace: '172.31.1.119  fpxapp'
  when: inventory_hostname in cdb_ips
  tags: [A34]

- block:
    - include_tasks: "{{ role_path }}/../go-no-go/tasks/update_db.yml"
      vars:
        update_db_act_no: "A35"
        tbl_update: "update BANKISLAMMBUAT1.IB_CONFIG_PARAM SET VALUE = '[\"http://localhost:9080/rib/logout/syncLogoutAndMenu\"]' WHERE module = 'login' and code = 'syncURL';"
        update_check: "select value from BANKISLAMMBUAT1.IB_CONFIG_PARAM where module = 'login' and code = 'syncURL';"
        expected_op: "http://localhost:9080/rib/logout/syncLogoutAndMenu"
      when: inventory_hostname==dr_db_server_ip
      tags:
       - A35

    - include_tasks: bring_up_app.yml
      vars:
        bring_up_App01_07: "A36"
      when: inventory_hostname in dr_app_ips
      tags: [A36]

    - include_tasks: check_App_URL.yml
      vars:
        bring_up_App01_07: "A36"
      when: inventory_hostname in dr_app_ips
      tags: [A36a]

    - include_tasks: start_ATM_Jompay.yml
      vars:
        start_ATM_Jompay_Listener: "A37"
      when: inventory_hostname in dr_app_ips
      tags: [A37]

    - include_tasks: start_CBS_Jompay.yml
      vars:
        start_CBS_Jompay: "A38"
      when: inventory_hostname in dr_app_ips
      tags: [A38]

    - include_tasks: enable_cronjob.yml
      vars:
        dr_enable_cron_job: "A39"
      when: inventory_hostname in dr_app_ips
      tags: [A39]
  become: yes
  
- include_tasks: Update_Tomcat_DB_Config.yml
  vars:
    dr_update_DB_config: "A40"
  when: inventory_hostname in dr_tomcat_ips
  tags: [A40]

- include_tasks: "{{ role_path }}/../go-no-go/tasks/restart_tomcat_service.yml"
  vars:
    bring_down_tomcat_services: "A41"
  when: inventory_hostname in dr_tomcat_ips
  tags: [A41]

- block:
    - include_tasks: Update_GO_Mobile_host_file.yml
      vars:
        update_GO_mobile_host: "A42"
        find2commentOut: '^172\.31\.123\.88(.*)$'
        line2Replace: '#172.31.123.88 mobilebanking.bankislam.com.my'
        find2uncomment: '^#172\.31\.123\.89(.*)$'
        line2Replace_2: '172.31.123.89 mobilebanking.bankislam.com.my'
      when: inventory_hostname in go_app_ips 
      tags: [A42]
  become: yes
