---
- block:
  - debug:
      msg: "{{ update_GO_mobile_host }}- updated /etc/hosts file"

  - name: "{{ update_GO_mobile_host }}-Comment the ip in /etc/hosts file"
    lineinfile:
      path: "{{ Go_mobile_host_path }}"
      regexp: "{{ find2commentOut }}"
      line: "{{ line2Replace }}"
      state: present
      backrefs: yes
    register: result

  - name: "{{ update_GO_mobile_host }}-Un-comment the ip in /etc/hosts file"
    lineinfile:
      path: "{{ Go_mobile_host_path }}"
      regexp: "{{ find2uncomment }}"
      line: "{{ line2Replace_2 }}"
      state: present
      backrefs: yes
    register: un_result

  - debug:
      msg: "{{ update_GO_mobile_host }}- IP address Updated."
    when: result.changed and un_result.changed

  - fail:
      msg: "{{ update_GO_mobile_host }}- IP address not Updated."
    when: not result.changed and not un_result.changed

  tags:
    - A42
    - B30a
