---

- include_tasks: "{{ role_path }}/../stop_services/tasks/update_db.yml"
  vars:
    update_db_act_no: B1
    tbl_update: "update BANKISLAMMBUAT1.tb_abnf_promotion_master set auth_status='A' where content_id='890' and screen_id='DownTime';"
    update_check: "select auth_status from BANKISLAMMBUAT1.tb_abnf_promotion_master where content_id='890' and screen_id='DownTime';"
    expected_op: "A"
  when: inventory_hostname==dr_db_server_ip
  tags:
    - B1

- include_tasks: "{{ role_path }}/../commons/tasks/cache_refresh.yml"
  vars:
    cache_refresh_act_no: B1.1
  when: inventory_hostname in DR_cache_refresh_server_ip
  tags:
    - B1.1

- block:
  - include_tasks: "{{ role_path }}/../stop_services/tasks/stop_apache_servers.yml"
    vars:
      stop_apache_act_no: B2
  become: yes
  become_user: root  
  when: inventory_hostname in DR_apache_server_ips
  tags:
    - B2

- include_tasks: "{{ role_path }}/../stop_services/tasks/stop_jboss_modules.yml"
  vars:
    stop_JBoss_module_act_no: B3
  when: inventory_hostname==DR_jboss_server_ip
  tags:
    - B3

- include_tasks: "{{ role_path }}/../stop_services/tasks/stop_jboss_instances.yml"
  vars:
    stop_JBoss_act_no: B4
  when: inventory_hostname in DR_jboss_instances_ip
  tags:
    - B4

- include_tasks: "{{ role_path }}/../checkpointing-1/tasks/stop_springcloud.yml"
  vars:
    stop_SC_act_no: B5
  when: inventory_hostname in DR_jboss_instances_ip
  tags:
    - B5
