---

- block:
    - name: "{{verifyFTPfromClient}} - Verify if the directory exists in server {{inventory_hostname}}" 
      win_stat:
        path: "{{ ftpdir2bVerifiedfromClient }}"
        get_checksum: no
      register: conn_test_path

    - fail:
        msg: "{{ verifyFTPfromClient}} - directory {{ ftpdir2bVerifiedfromClient }} doesn't exist in server {{inventory_hostname}}!"
      when: not conn_test_path.stat.exists

    - name: "{{ verifyFTPfromClient }} - Check for {{ file_list_client }} existence"
      win_stat:
        path: "{{ file_list_client }}"
        get_checksum: no
      register: fileReg
      failed_when: not fileReg.stat.exists

    - name: "{{ verifyFTPfromClient }} - Read pre-FTP file list"
      win_shell: 'type {{file_list_client}}'
      register: clientfiles

    - set_fact:
        preFtpFilesInClientDir: "{{ clientfiles.stdout_lines }}"

    - name: "{{ verifyFTPfromClient}} - Pre-FTP: List of existing files in {{ ftpdir2bVerifiedfromClient }}"
      debug:
        var: preFtpFilesInClientDir

    - name: "{{ verifyFTPfromClient }} - Post-FTP retrieve list of files in {{ ftpdir2bVerifiedfromClient }}"
      win_find:
        paths: "{{ ftpdir2bVerifiedfromClient }}"
        file_type: file
      register: newFilesInDir

    - name: "{{ verifyFTPfromClient }} - Build list of files post-FTP"
      set_fact:
        postFtpFilesInClientDir: "{{ postFtpFilesInClientDir | default([]) + [item.filename] }}"
      no_log: true
      loop: "{{ newFilesInDir.files }}"

    - name: "{{ verifyFTPfromClient }} - Post-FTP: List of all files in {{ ftpdir2bVerifiedfromClient }}"
      debug:
        var: postFtpFilesInClientDir

    - set_fact:
        newFtpFilesInClientDir: "{{ postFtpFilesInClientDir | difference(preFtpFilesInClientDir) }}"

    - name: "{{ verifyFTPfromClient }} - Stop if no files received from client"
      fail:
        msg: "No files received from client in {{ inventory_hostname }}. Please check!"
      when: newFtpFilesInClientDir | length == 0

    - name: "{{ verifyFTPfromClient }} - Post-FTP: There are {{ newFtpFilesInClientDir | length }} new files received from client in {{ ftpdir2bVerifiedfromClient }}"
      debug:
        var: newFtpFilesInClientDir

    - name: "{{ verifyFTPfromClient }} - Proceed to delete newly FTP'd files from client"
      win_file:
        path: "{{ ftpdir2bVerifiedfromClient }}\\{{ item }}"
        state: absent
      loop: "{{ newFtpFilesInClientDir }}"

  tags:
    - A16c
    - B18c
