---
- block:
  - debug:
      msg: "{{ bring_up_App01_07 }}- Bring up the apps WebSphere services"

  - stat:
      path: "{{ app_server_start_script }}"
    register: app_server_path

  - fail:
      msg: "{{ bring_up_App01_07 }}- WebSphere services script path {{ app_server_start_script }}  doesn't exist."
    when: not app_server_path.stat.exists

  - name: "{{ bring_up_App01_07 }}- Bring up the App01-App9"
    command: ksh "{{ app_server_start_script }}"
    register: start_result
    ignore_errors: yes

  - debug:
      var: start_result.stdout

  - set_fact:
      fail2start: false

  - set_fact:
      need2check: false

  - set_fact:
      fail2start: true
    when: "not start_result.stdout | regex_search('.*ADMU3000I: Server.*open for e-business.*$', multiline=True)"

  - set_fact:
      need2check: true
    when: "start_result.stdout | regex_search('.*ADMU3027E: An instance of the server may already be running.*$', multiline=True)"

  - block:
    - name: "Display message to request Apps personnel to check if App services are indeed started"
      fail:
        msg: "Either WebSphere services already started, or there is connectivity problem. Please check!"
      when: need2check == true
    when: fail2start == true

  - name: "Display failure message if services not started"
    fail:
      msg: "Not able to start WebSphere services."
    when: fail2start == true

  - debug:
      msg: "{{ bring_up_App01_07 }}- WebSphere services started."

  become: yes
  tags:
    - A36
    - B14
    - B15
    - B16
    - B17
    - B18
    - B19
    - B20
    - B21
    - B22
    - B23

