---
- include_tasks: "{{ role_path }}/../pre_activities/tasks/DBSwing.yml"
  vars:
    actNo: "A4"
    dbname: "TBD"
  when: inventory_hostname in gir_db_ips
  tags: [A4]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/mountRecordingStorage.yml" 
  vars:
    actNo: "A6"
    username: "ccgirlinuser"
    password: "nKsr#J9f"
    file_mode: 0777
    dir_mode: 0777
    fileserver: DRCCFSVR01
    filesystem: "/recording/mnt/recording"
  when: inventory_hostname in dr_webdav_ips
  tag: [A6]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A10"
    svc_name: "{{ item }}"
    action: "stop"
  loop: ["BOEXI40Tomcat","BOEXI40SIAPRDCCADMUI01"]
  when: inventory_hostname in ccm_ips
  tags: [A10]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "A12"
    svc_name: "{{ item }}"
    svc_state: "stopped"
  loop: ["gir","elasticsearch"]  
  when: inventory_hostname in gir_db_ips 
  tags: [A12]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "A13"
    svc_name: httpd
    svc_state: "stopped"
  when: inventory_hostname in webdav_ips
  tags: [A13]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A14"
    svc_name: "IIS Admin Service"
    action: "stop"
  when: inventory_hostname in sm_ips
  tags: [A14]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A15"
    svc_name: "{{ item }}"
    action: "stop"
  loop: ["SCServer64","ConfigServer64_1","ConfigServer64"]
  when: inventory_hostname in cfg_ips[1]
  tags: [A15]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A15"
    svc_name: "{{ item }}"
    action: "stop"
  loop: ["SCServer64","ConfigServer64_1","ConfigServer64"]
  when: inventory_hostname in cfg_ips[0]
  tags: [A15]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/verifyDBObjects.yml"
  vars:
    actNo: "A16"
    dbname: "genocsdb"
    objects: "tables"
  when: inventory_hostname in dr_rpt_db_ips
  tags: [A16]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A18"
    svc_name: "ConfigServer64"
    action: "start"
  when: inventory_hostname in dr_cfg_ips
  tags: [A18]

###
- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkLineExistence.yml"
  vars:
    actNo: "A18"
    path: F:\gcti_logs\cfgsvr_dr_p
    line2check: "Port 2020 opened for listening"
  when: inventory_hostname in dr_cfg_ips
  tags: [A18]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A19"
    svc_name: "ConfigServer64_1"
    action: "stop"
  when: inventory_hostname in dr_cfg_ips
  tags: [A19.1]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/editRegistryEntry.yml"
  vars:
    actNo: "A19"
    entryPath: HKLM:\System\CurrentControlSet\Services\ConfigServer64_1
    entryToEdit: ImagePath
    valueToEdit: '"E:\GCTI\Configuration Server\cfgproxy_dr_p" -host DRCCCR01 -port 2020 -app cfgproxy_dr_p -service ConfigServer64_1 -l 7260@DRCCCR01'
    entryType: expandstring
  when: inventory_hostname in dr_cfg_ips
  tags: [A19.2]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A19"
    svc_name: "ConfigServer64_1"
    action: "start"
  when: inventory_hostname in dr_cfg_ips
  tags: [A19.3]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkLineExistence.yml"
  vars:
    actNo: "A19"
    path: F:\gcti_logs\cfgproxy_dr_p\
    line2check: "Port 2080 opened for listening"
  when: inventory_hostname in dr_cfg_ips
  tags: [A19.4]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A20"
    svc_name: "SCServer64"
    action: "start"
  when: inventory_hostname in dr_cfg_ips
  tags: [A20]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkPrimaryDB.yml"
  vars:
    actNo: "A21"
    dbname: "TBD"
    status: "primary"
  when: inventory_hostname in dr_cfg_ips
  tags: [A21.1]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A21"
    svc_name: "{{ item }}"
    action: "start"
  loop: ["BOEXI40Tomcat","BOEXI40SIAPRDCCADMUI01"]
  when: inventory_hostname in dr_cfg_ips
  tags: [A21.2]

# wait for the services to start in A21.2
- pause:
    seconds: 10
  tags: always

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkListeningPort.yml"
  vars:
    actNo: "A21"
    hostIp: 127.0.0.1
    portNo: 6400
  when: inventory_hostname in dr_cfg_ips
  tags: [A21.2]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "A21"
    urlStr: https://localhost:8080/BOE/BI
  when: inventory_hostname in dr_cfg_ips
  tags: [A21.2]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "A22"
    svc_name: "IIS Admin Service"
    action: "start"
  when: inventory_hostname in dr_ga_ips + dr_sm_ips + dr_tpin_ips
  tags: [A22]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "A22"
    urlStr: "https://localhost/wcm"
  when: inventory_hostname in dr_ga_ips
  tags: [A22]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "A22"
    urlStr: "https://localhost/speechminer"
  when: inventory_hostname in dr_sm_ips[0]
  tags: [A22]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "A22"
    urlStr: "http://172.31.127.200/indexer"
  when: inventory_hostname in dr_sm_ips[1]
  tags: [A22]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "A22"
    urlStr: "http://localhost/8384/CustomerSearch/CustomerSearchWBIC.aspx?nric=<nric>"
  when: inventory_hostname in dr_tpin_ips
  tags: [A22]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkAndReplaceLine.yml"
  vars:
    actNo: "A24"
    file: "/Genesys/RWS/Config/application.yaml"
    line2check: "syncNode: \w+"
    line2replace: "syncNode: true"
  when: inventory_hostname in dr_gir_db_ips[0]
  tags: [A24]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "A24"
    svc_name: gir
    svc_state: "started"
  when: inventory_hostname in dr_gir_db_ips[0]
  tags: [A24]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "A26"
    svc_name: gir
    svc_state: "restarted"
  when: inventory_hostname in dr_gir_db_ips[0]
  tags: [A26]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/runShellCommand.yml"
  vars:
    actNo: "A26"
    cmdStr: >
      "curl -u ops:ops --insecure "
      "https://rwscc.bankislam.com.my:8443/api/v2/ops/genesys-environments/ON_PREMISE_ENVIRONMENT "
      "| python -m json.too"
  when: inventory_hostname in dr_gir_db_ips[0]
  tags: [A26]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "A27"
    svc_name: gir
    svc_state: "started"
  when: inventory_hostname in dr_gir_db_ips[1] + dr_gir_db_ips[2]
  tags: [A27]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "A28"
    svc_name: elasticsearch
    svc_state: "started"
    when: inventory_hostname in dr_gir_db_ips
  tags: [A28]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "A29"
    svc_name: httpd
    svc_state: "started"
  when: inventory_hostname in dr_webdav_ips
  tags: [A29]
