---
- block:
  - debug:
      msg: "{{ bring_up_web1_web6 }}- Bring up Maintenance page on Web01-Web06"

  - stat:
      path: "{{ web_server_bring_up_maintenance_script }}"
    register: web_maintenance_up_script

  - fail:
      msg: "{{ bring_up_web1_web6 }}- Web server bring up maintenance script path {{ web_server_bring_up_maintenance_script }} doesn't exist."
    when: not web_maintenance_up_script.stat.exists

  - name: "{{ bring_up_web1_web6 }}- Bring up the web01 to web06 maintenance pages"
    command: "{{ web_server_bring_up_maintenance_script }}"

  - pause:
      seconds: "{{pause_duration}}"

  - name: "{{ bring_up_web1_web6 }}- Check the maintenance page URL"
    fail:
      msg: "{{ bring_up_web1_web6 }}- {{ ib_web_url }} is either not defined or is empty"
    when: ib_web_url is not defined or ib_web_url|trim==""

  - name: "{{ bring_up_web1_web6 }}- Verifying the url {{ ib_web_url }}"
    uri:
      url: "{{ ib_web_url }}"
      status_code: 200
      validate_certs: no
    register: validate_result

  - name: "{{ bring_up_web1_web6}}- Web-Appserver: Report the status of maintenance page"
    debug:
      msg: "{{ bring_up_web1_web6 }}- Web maintenance page verification is successful."
    when: validate_result.status == 200

  - fail:
      msg: "{{ bring_up_web1_web6 }}- Maintenance page is not up."
    when: validate_result.status != 200

  tags:
    - A1
    - A2
    - A3
    - A4
    - A5
    - A6
    - A32
    - B3

