---
- include_tasks: "{{ role_path }}/../run_prerequisite/tasks/update_db.yml"
  vars:
    - query: "update tb_abnf_promotion_master set auth_status='A' where content_id='992' and screen_id='Downtime';commit; --put up downtime"
    - expected_op: "auth_status='A'"
  when: inventory_hostname==dr_db_ip

- include_tasks: "{{ role_path }}/../run_prerequisite/tasks/stop_apache_servers.yml"
  when: inventory_hostname in prod_apache_server_ips

- include_tasks: "{{ role_path }}/../run_prerequisite/tasks/stop_jboss_modules.yml"
  when: inventory_hostname==dr_jboss_server_ip

- include_tasks: "{{ role_path }}/../run_prerequisite/tasks/stop_jboss_instances.yml"
  when: inventory_hostname in dr_jboss_instances_ip

- include_tasks: "{{ role_path }}/../checkpointing-1/tasks/stop_springcloud.yml"
  when: inventory_hostname in dr_jboss_instances_ip

- include_tasks: "{{ role_path }}/../checkpointing-2/tasks/start_springcloud.yml"
  when: inventory_hostname in dr_jboss_instances_ip

- include_tasks: "{{ role_path }}/../checkpointing-2/tasks/start_jboss.yml"
   when: inventory_hostname in dr_jboss_instances_ip


- include_tasks: "{{ role_path }}/../checkpointing-2/tasks/start_jboss_modules.yml"
   when: inventory_hostname==dr_jboss_server_ip

- include_tasks: "{{ role_path }}/../checkpointing-2/tasks/start_apache_servers.yml"
   when: inventory_hostname in prod_apache_server_ips

## Checking the login
- include_tasks: "{{ role_path }}/../commons/tasks/check_url.yml"
  vars:
    - url: "{{ mobile_admin_login_url }}"
