---

- hosts:
    - aix,solaris
  gather_facts: no

  tasks:
    - name: "Initial connectivity test against all managed_hosts before actual DRP"
      shell: |
         #echo "`id | awk '{print $1}' | awk -F'(' '{print $2}' | sed 's/)//g'` "
         echo "`whoami`"
      ignore_errors: yes
      register: conn_test_result

    - shell:
        echo "The connecting user is {{conn_test_result.stdout}}. Connection into {{inventory_hostname}} is successful"
      ignore_errors: yes
      register: conn_test_result2

    - debug:
        var: conn_test_result2.stdout

