---

- hosts:
    - all
  gather_facts: false
  become_method: runas
  vars:
    ansible_become_password: "{{ ans_password }}"

  tasks:
   - include_role:
       name: pre_activities
     tags: [P8,P12]
  
  any_errors_fatal: true


