---

- hosts:
    - all
  gather_facts: false
  become_method: runas
  vars:
    ansible_become_password: "{{ ans_password }}"

  tasks:
   - include_role:
       name: swing_over_DR
     tags: [A5.1,A5.2,A5.3,A10,A11,A15,A16a,A16c,A23]
  
  any_errors_fatal: true


