---

bring_up_web1_web6: "A32"
Update_host_CDB_Server: "A34"
update_db_act_no: "A35"
bring_up_App01_07: "A36"
start_ATM_Jompay_Listener: "A37"
start_CBS_Jompay: "A38"
dr_enable_cron_job: "A39"
dr_update_DB_config: "A40"
bring_down_tomcat_services: "A41"
update_GO_mobile_host: "A42"

find2commentOut: "{{ prod2dr_line_to_commentOut }}"
line2Replace: "{{ prod2dr_line_to_update }}"
find2uncomment: "{{ prod2dr_line_to_uncomment }}"
line2Replace_2: "{{ prod2dr_line_to_update_2 }}"

CDB_find_line: "{{ prod2dr_CDB_find_line }}"
CDB_line2Replace: "{{ prod2dr_CDB_line_to_replace }}"

