---
- block:
  - debug:
      msg: "{{ bring_up_web1_web6 }}- Bring up Maintenance page on Web01-Web06"

  - stat:
      path: "{{ web_server_bring_up_maintenance_script }}"
    register: web_maintenance_up_script

  - fail:
      msg: "{{ bring_up_web1_web6 }}- Web server bring up maintenance script path {{ web_server_bring_up_maintenance_script }} doesn't exist."
    when: not web_maintenance_up_script.stat.exists

  - name: "{{ bring_up_web1_web6 }}- Bring up the web01 to web06 maintenance pages"
    command: "{{ web_server_bring_up_maintenance_script }}"

  - pause:
      seconds: "{{pause_duration}}"

  - name: "{{ bring_up_web1_web6 }}- URL to check is as follows"
    set_fact:
      url_2b_verify: 'https://{{inventory_hostname}}/rib/verify.html'

  - name: "{{ bring_up_web1_web6 }}- Verifying the url {{ url_2b_verify }}"
    uri:
      url: "{{ url_2b_verify }}"
      status_code: 200
      validate_certs: no
    register: validate_result

  - debug:
      var: validate_result

  - name: "{{ bring_up_web1_web6 }}- Web-Appserver: Report the status of maintenance page"
    debug:
      msg: "{{ bring_up_web1_web6 }}- Web maintenance page verification is successful. The page is up."
    when: validate_result.status == 200

  - fail:
      msg: "{{ bring_up_web1_web6 }}- Maintenance page is not up."
    when: validate_result.status != 200

  become: yes
  tags:
    - A1
    - A2
    - A3
    - A4
    - A5
    - A6
    - A32
    - B3

