---
- block:
    - include_tasks: bring_up_web.yml
      vars:
        bring_up_web1_web6: "A1-A6"
      when: inventory_hostname in prod_web_ips
      tags: [A1,A2,A3,A4,A5,A6]

    - include_tasks: bring_down_app.yml
      vars:
        bring_down_App1_App9: "A9-A17"
      when: inventory_hostname in prod_app_ips
      tags: [A9,A10,A11,A12,A13,A14,A15,A16,A17]

    - include_tasks: check_App_URL.yml
      vars:
        bring_down_App1_App9: "A9-A17"
      when: inventory_hostname in prod_app_ips
      tags: [A9a]

    - include_tasks: stop_ATM_Jompay.yml
      vars:
        stop_ATM_Jompay: "A18"
      when: inventory_hostname in prod_app_ips
      tags: [A18]

    - include_tasks: stop_CBS_Jompay.yml
      vars:
        stop_CBS_Jompay: "A19"
      when: inventory_hostname in prod_app_ips
      tags: [A19]

    - include_tasks: disable_cron_job.yml
      vars:
        disable_cron_job_IB_App: "A20"
      when: inventory_hostname in prod_app_ips
      tags: [A20,A20.05,A20.1,A20.2]

    - include_tasks: stop_IB_Report_Quartz.yml
      vars:
        stop_IB_report_quartz: "A21"
      when: inventory_hostname in prod_app_ips
      tags: [A21]

    - include_tasks: update_db.yml
      vars:
        update_db_act_no: "A22"
        tbl_update: "update BANKISLAMMBUAT1.IB_Test set auth_status='A' where content_id='890' and screen_id='DownTime';"
        update_check: "select auth_status from BANKISLAMMBUAT1.IB_Test where content_id='890' and screen_id='DownTime';"
        expected_op: "A"
      when: inventory_hostname==prod_db_server_ip
      tags:
       - A22
  become: yes
  
- include_tasks: restart_tomcat_service.yml
  vars:
    bring_down_tomcat_services: "A23"
  when: inventory_hostname in prod_tomcat_ips
  tags: [A23]

