---

#Playbook to complete the rest of the pre-requisistes from P11 to P16
- hosts:
    - all
  gather_facts: no
  become: yes
  become_user: uatmbapp

  tasks:
   - include_role:
       name: stop_services
     tags: [P11,P11.1,P12,P13,P14,P16]
  
  any_errors_fatal: true
