---
- hosts: all
  gather_facts: false
  become: true
  tasks:

  - name: Change the defult jenkins port 8080 to 9081
    replace:
      dest: /etc/sysconfig/jenkins
      regexp: 'JENKINS_PORT="8080"'
      replace: 'JENKINS_PORT="9085"'
      backup: yes
    debug:
      msg: "Jenkis Default port changed successfully"
 
  - name: start jenkins
    systemd:
     name: jenkins
     state: reloaded
    debug:
      msg: "Jenkis reloaded successfully"

  - name: Ensure port 9085 added to firewalld
    firewalld:
      port: 9085/tcp
      state: enabled
      permanent: yes
      immediate: yes
    debug:
      msg: "Jenkis port added to firewalld"