---
- block:
  - debug:
      msg: "{{ bring_up_App01_07 }}- Bring up the apps WebSphere services"

  - stat:
      path: "{{ app_server_start_script }}"
    register: app_server_path

  - fail:
      msg: "{{ bring_up_App01_07 }}- WebSphere services script path {{ app_server_start_script }}  doesn't exist."
    when: not app_server_path.stat.exists

  - name: "{{ bring_up_App01_07 }}- Bring up the App01-App9"
    command: ksh "{{ app_server_start_script }}"
    register: start_result
    ignore_errors: yes
  
  - debug:
      var: start_result.stdout

  - set_fact:
      str_result1: "ADMU3027E: An instance of the server may already be running: server1"
      str_result2: "ADMU3000I: Server server1 open for e-business"
 
  - set_fact:
      fail2start: "NO"

  - set_fact:
      fail2start: "YES"
    when: str_result1 not in start_result.stdout

  - block:
      - name: "Display failure message if services not started"
        fail:
          msg: "Not able to start WebSphere services."
        when: str_result2 not in start_result.stdout
    when: fail2start == 'YES'

  - debug:
      msg: "{{ bring_up_App01_07 }}- WebSphere services started."

  tags:
    - A36
    - B14
    - B15
    - B16
    - B17
    - B18
    - B19
    - B20
    - B21
    - B22
    - B23


