---
- block:

    - name: "{{checkSync}} - Verify if the directory exists in primary server {{checkDirFileSync_priServ}}" 
      win_stat:
        path: "{{ checkDirFileSync_dirLoc }}"
      register: conn_test_path

    - fail:
        msg: "{{ checkSync}}- directory {{ checkDirFileSync_dirLoc }} doesn't exist in server {{checkDirFileSync_priServ}}."
      when: not conn_test_path.stat.exists

    - name: "{{checkSync}} - Retrieve file count in the directory {{ checkDirFileSync_dirLoc }} of the primary server {{checkDirFileSync_priServ}}"
      win_command: powershell.exe -
      args:
        stdin: cd -Path {{checkDirFileSync_dirLoc}} -PassThru ; $fileCount = (Get-ChildItem -File | Measure-Object).Count ; Write-Host "fileCount $fileCount"
      register: result
      tags: [B0]

    - set_fact:
        fileCount: "{{ item.split()[1] }}"
      when: item | regex_search('fileCount')
      with_items: "{{result.stdout_lines}}"

    - debug:
        var: fileCount
  when: inventory_hostname == checkDirFileSync_priServ
  tags:
    - P6
    - B0

- block:
    - name: "{{checkSync}} - Verify if the directory exists in DR server {{checkDirFileSync_drServ}}"
      win_stat:
        path: "{{ checkDirFileSync_dirLoc }}"
      register: conn_test_path

    - fail:
        msg: "{{ checkSync}}- directory {{ checkDirFileSync_dirLoc }} doesn't exist in server {{checkDirFileSync_drServ}}."
      when: not conn_test_path.stat.exists

    - name: "{{checkSync}} - Retrieve file count in the directory {{ checkDirFileSync_dirLoc }} of the primary server {{checkDirFileSync_drServ}}"
      win_command: powershell.exe -
      args:
        stdin: cd -Path {{checkDirFileSync_dirLoc}} -PassThru ; $fileCount = (Get-ChildItem -File | Measure-Object).Count ; Write-Host "fileCount $fileCount"
      register: result
      tags: [P6,B0]

    - set_fact:
        fileCount: "{{ item.split()[1] }}"
      when: item | regex_search('fileCount')
      with_items: "{{result.stdout_lines}}"

    - debug:
        var: fileCount
  when: inventory_hostname == checkDirFileSync_drServ
  tags:
    - P6
    - B0


- block:
    - set_fact:
        priServFileCount: "{{ hostvars[checkDirFileSync_priServ]['fileCount'] }}"
        drServFileCount: "{{ hostvars[checkDirFileSync_drServ]['fileCount'] }}"

    - name: "{{checkSync}} - Verify if file count is tally"
      debug:
        msg: "both servers {{checkDirFileSync_priServ}} and {{checkDirFileSync_drServ}} are having same count of files"
      when: priServFileCount == drServFileCount

    - fail:
        msg: "Files count between server {{checkDirFileSync_priServ}} and {{checkDirFileSync_drServ}} is not the same!"
      when: priServFileCount != drServFileCount
   
  tags:
    - P6
    - B0

