---

#st stands for status
#st_bank_script_path refers to the status of bank script path
- stat:
    path: "{{ jboss_start_banking_script }}"
  register: st_bank_script_path

- fail:
    msg: "Start banking script {{ jboss_start_banking_script }} doesn't exist"
  when: not st_bank_script_path.stat.exists

#verify if the stop reporting script exist or not
- stat:
    path: "{{ jboss_start_reporting_script }}"
  register: st_reporting_script_path

- fail:
    msg: "Start reporting script {{ jboss_start_reporting_script }} doesn't exist"
  when: not st_reporting_script_path.stat.exists

#verify if the stop admin script exist or not
- stat:
    path: "{{ jboss_start_admin_script }}"
  register: st_admin_script_path

- fail:
    msg: "Start banking script {{ jboss_start_admin_script }} doesn't exist"
  when: not st_admin_script_path.stat.exists


- stat:
    path: "{{ jboss_start_reporting_instance }}"
  register: st_report_instance_path

- fail:
    msg: "Start reporting instance {{ jboss_start_reporting_instance }} doesn't exist"
  when: not st_report_instance_path.stat.exists


- name: "Starting banking module"
  shell:
    cmd: "{{ jboss_start_banking_script }}"

- name: "Starting reporting module"
  shell:
    cmd: "{{ jboss_start_reporting_script }}"

- name: "Starting  admin module"
  shell:
    cmd: "{{ jboss_start_admin_script }}"

- name: "Starting  reporting instance"
  shell:
    cmd: "{{ jboss_start_reporting_instance }}"

## verify if the process have started.
#Verify if the banking, admin and reporting processes are started, by retrieving the PIDs
- name: "Check if banking module has started"
  pids:
    name: Banking
    #mod is acronym for module. Example admin_mod_status refers to admin module status
  register: bank_mod_status

- name: "Check if reporting module has started"
  pids:
    name: Reporting
    #mod is acronym for module. Example admin_mod_status refers to admin module status
  register: report_mod_status

- name: "Check if admin module has started"
  pids:
    name: Admin
    #mod is acronym for module. Example admin_mod_status refers to admin module status
  register: admin_mod_status

- fail:
    msg: "Banking module has not started. Please check."
  when:  bank_mod_status.pids|length == 0

- fail:
    msg: "Reporting module has not started. Please check."
  when:  report_mod_status.pids|length == 0

- fail:
    msg: "Admin module has not started. Please check."
  when:  admin_mod_status.pids|length == 0

- debug:
    msg: "Banking, reporting and admin modules have successfully started."
