---

- block:
    - set_fact:
        mirrorSwitchOver: >
          ALTER DATABASE {{DB2BSwitchOver}} SET SAFETY FULL;
          ALTER DATABASE {{DB2BSwitchOver}} SET PARTNER FAILOVER;

    - name: "{{ DBMirroring }} SwitchOver database {{DB2BSwitchOver}} via Mirroring"
      win_shell: "invoke-sqlcmd -Query \"{{mirrorSwitchOver}}\" -ServerInstance \"{{SQLServerInstance}}\" -Database \"{{DBName}}\""
      register: response

    - debug:
        msg: "{{ DBMirroring }} - Mirroring failover status is {{ response.stdout }}"

  tags:
    - A7.2
    - B3.2
