---
- block:
    - set_fact:
        svc_state: 'stopped'
        expected_state: 'stopped'
      when: action == 'stop'

    - set_fact:
        svc_state: 'started'
        expected_state: 'running'
      when: action == 'start'

    - name: "{{ actNo }} - To {{ action }} {{ svc_name }} service in {{ inventory_hostname }}"
      win_service:
        name: "{{ svc_name }}"
        state: "{{ svc_state }}"
      until: svc_stat.state == expected_state
      retries: 3
      delay: 5
      register: svc_stat

    - debug:
        var: svc_stat
      
    - debug:
        msg: "{{ actNo }} - The service {{ svc_name }} is {{ expected_state }} in {{ inventory_hostname }}"
      when: svc_stat.state == expected_state
      
    - fail:
        msg: "{{ actNo }} - The service {{ svc_name }} is not {{ expected_state }} in {{ inventory_hostname }}. Please check!"
      when: svc_stat.state != expected_state
      
  tags:
    - P15-P17
    - A7
    - B4
    - B12
