---
- block:
    - name: "{{ actNo }} - To verify {{ svc_name }} service in {{ inventory_hostname }}"
      win_service:
        name: "{{ svc_name }}"
      register: svc_stat
      #failed_when: svc_stat is not defined
      #become: yes
      #become_user: ansible

    - debug:
        msg: "{{ actNo }} - The service {{ svc_name }} is {{ svc_stat.state }} in {{ inventory_hostname }}"
      when: svc_stat.name is defined
      
    - fail:
        msg: "{{ actNo }} - The service {{ svc_name }} does not exist in {{ inventory_hostname }}"
      when: svc_stat.name is not defined
      
    - fail:
        msg: "{{ actNo }} - The service {{ svc_name }} is not running in {{ inventory_hostname }}. Please check!"
      when: svc_stat.state is not defined
      
  tags:
    - P17
    - A5
    - A8
    - B6
    - B10
    - B13
