---
- block:
    - name: "{{del_authorized_keys}} - Search for public key of Ansible Controller in authorized_keys, and delete the line"
      lineinfile:
        path: $HOME/.ssh/authorized_keys
        search_string: "UATANSSVR01"
        state: absent
      register: del_status

    - name: Send email regarding del_status
      mail:
        host: 10.20.33.11
        port: 25
        from: ib_pt@bankislam.com.my
        to: smreza@bankislam.com.my
        subject: "{{del_authorized_keys}} - Search for public key of Ansible Controller in authorized_keys, and delete the line"
        body: Deletion of key for UATANSSVR01 {{ del_status }}
      delegate_to: localhost

    - debug:
        msg: "{{del_authorized_keys}} - SSH public key is removed from {{inventory_hostname}}"
      when: del_status is changed
      
    - fail: 
        msg: "{{del_authorized_keys}} - SSH public key is not removed from {{inventory_hostname}}. Please check!"
      when: del_status is not changed
     
  tags: 
    - B46
