---
- block:
  - debug:
      msg: "Check the Server IP, IP shall be {{ IIB_MQ_DRC }}"
  
  - name: get and check the ip adress
    shell: "{{ IP }}"
    register: ip
    become: yes
    become_user: root
  - debug:
      var: ip

  - fail:
      msg: " {{ IIB_MQ_DRC }} and {{ ip }} not matched."
    when: not ip.stdout_lines

  - debug:
      msg: " IP shall be {{ IIB_MQ_DRC }} and this server IP is {{ ip.stdout }}, IP Address is Matched."
    when: ip.stdout_lines  
