---
- block:
    - include_tasks: Check_ip.yml
      when: inventory_hostname in IIB_DR_ips
      tags: [A1.1]

    - include_tasks: Stop_QMLPPIB.yml
      when: inventory_hostname in IIB_DR_ips
      tags: [A1.2]

    - include_tasks: Start_QMLPPIB.yml
      when: inventory_hostname in IIB_DR_ips
      tags: [A1.3] 

    - include_tasks: verify_QMLPPIB.yml
      when: inventory_hostname in IIB_DR_ips
      tags: [A1.4]   

 

