---
- block:
    - include_tasks: Check_ip.yml
      when: inventory_hostname in IIB_DR_ips
      tags: [A1.1]

    - include_tasks: bring_down_app.yml
      when: inventory_hostname in app_ips
      tags: [A9,A10,A11,A12,A13,A14,A15,A16,A17]

  become: yes
 

