---
- block:
  - debug:
      msg: "Start the QMLPPIB"
  
  - name: QMLPPIB is starting...
    command: chdir=/opt/IBM/iib-10.0.0.7/ {{ item }}
    with_items:
    - strmqm QMLPPIIB
    - ./iib mqsistart IBNODE
    register: QMLPPIB_start_result
  
  - wait_for:
      timeout: "{{ pause_duration }}"

  - debug:
      var: QMLPPIB_start_result

#  - name: "QMLPPIB Start process faild "
#    fail:
#      msg: "not able to start QMLPPIB"
#    when: QMLPPIB_start_result.stdout | trim == '0'

  - debug:
      msg: "Successfully Started the QMLPPIB "
  
  tags:
    - A1.3