---
- block:
  - debug:
      msg: "Stop the QMLPPIB"
  
  - name: QMLPPIB is stopping...
    command: chdir=/opt/IBM/iib-10.0.0.7/ {{ item }}
    with_items:
    - endmqm QMLPPIIB
    - ./iib mqsistop IBNODE
    register: QMLPPIB_stop_result
  
  - wait_for:
      timeout: "{{ pause_duration }}"

  - debug:
      var: QMLPPIB_stop_result

  - fail:
      msg: "not able to stop QMLPPIB"
    when: QMLPPIB_stop_result.stdout | trim == '0'

  - debug:
      msg: "Successfully Stop the QMLPPIB "
  
  tags:
    - A1.2