---

- include_tasks: "{{ role_path }}/../checkpointing-2/tasks/start_springcloud.yml"
  when: inventory_hostname in primary_jboss_instances_ip
  tags:
    - B13

- include_tasks: "{{ role_path }}/../checkpointing-2/tasks/start_jboss.yml"
  when: inventory_hostname in primary_jboss_instances_ip
  tags:
    - B14

- include_tasks: "{{ role_path }}/../checkpointing-2/tasks/start_jboss_modules.yml"
  when: inventory_hostname==primary_jboss_server_ip
  tags:
    - B15
    - B16

- block:
  - include_tasks: "{{ role_path }}/../checkpointing-2/tasks/start_apache_servers.yml"
  become: yes
  become_user: root
  when: inventory_hostname in primary_apache_server_ips
  tags:
    - B17

## Checking the login
- block:
  - include_tasks: "{{ role_path }}/../commons/tasks/check_url.yml"
    vars:
      - url: "{{ mobile_admin_login_url }}"
  become: yes
  become_user: root
  when: inventory_hostname in primary_jboss_instances_ip
  tags:
    - B18

