---
- block:
  - stat:
      path: "{{ jboss_eap_path }}"
    register: st_jboss_eap

  - fail:
      msg: "{{ stop_JBoss_act_no }}- Path {{ jboss_eap_path }} doesn't exist"
    when: not st_jboss_eap.stat.exists

  - name: "{{ stop_JBoss_act_no }}- Stopping JBoss instance"
    shell:
      chdir: "{{ jboss_eap_path }}"
      cmd: bash -l ./stopjb.sh
    ignore_errors: yes

  - pause:
      seconds: "{{ pause_duration }}"

  #Verify if the jboss is stopped or not
  - name: "{{ stop_JBoss_act_no }}- Check if Jboss instance is stopped"
    shell: ps -ef | grep jboss
    ignore_errors: yes
    changed_when: false
    register: jboss_status

  - fail:
      msg: "{{ stop_JBoss_act_no }}- Jboss instance is not stopped. Please check."
    when: '"Djboss.domain.master.address" in jboss_status.stdout'

  - debug:
      msg: "{{ stop_JBoss_act_no }}- Jboss instance is successfully stopped."

  tags:
    - P14
    - B4
    - A3
