---
- block:
  - stat:
      path: "{{ jboss_eap_path }}"
    register: st_jboss_eap

  - fail:
      msg: "{{ start_JBoss_act_no }}- Path {{ jboss_eap_path }} doesn't exist"
    when: not st_jboss_eap.stat.exists

  - name: "{{ start_JBoss_act_no }}- Stopping JBoss instance"
    shell:
      chdir: "{{ jboss_eap_path }}"
      cmd: bash -l ./stopjb.sh
    ignore_errors: yes

  - pause:
      seconds: "{{ pause_duration }}"

  - name: "{{ start_JBoss_act_no }}- Verifying if Jboss instance is stopped"
    shell: ps -ef | grep jboss
    ignore_errors: yes
    register: jboss_status

  - fail:
      msg: "{{ start_JBoss_act_no }}- Jboss instance has not stopped. Please check."
    when: '"Djboss.domain.master.address" in jboss_status.stdout'

  - debug:
      msg: "{{ start_JBoss_act_no }}- Jboss instance is successfully stopped."

  - name: "{{ start_JBoss_act_no }}- Starting JBoss instance"
    shell:
      chdir: "{{ jboss_eap_path }}"
      cmd: bash -l ./startjb.sh

  #Sleep for 5 seconds
  - pause:
      seconds: "{{ pause_duration }}"

  #Verify if the jboss has started or not
  - name: "{{ start_JBoss_act_no }}- Verifying if Jboss instance has started"
    shell: ps -ef | grep jboss
    ignore_errors: yes
    register: jboss_status

  - fail:
      msg: "{{ start_JBoss_act_no }}- Jboss instance has not started. Please check."
    when:  not '"Djboss.domain.master.address" in jboss_status.stdout'

  - debug:
      msg: "{{ start_JBoss_act_no }}- Jboss instance has successfully started."
  
  tags:
    - B14
    - A12
