---

- hosts:
    - win_test
  gather_facts: false
  become_method: runas
  vars:
    ansible_become_password: "{{ ans_password }}"

  tasks:
    - name: "Test variable"
      win_command: powershell.exe -
      args:
        stdin: cd -Path C:\output -PassThru ; $fileCount = (Get-ChildItem -File | Measure-Object).Count ; Write-Host "fileCount $fileCount"
      register: result

    - set_fact:
        fileCount: "{{ item.split()[1] }}"
      when: item | regex_search('fileCount')
      with_items: "{{result.stdout_lines}}"

    - debug:
        var: fileCount

