---

- hosts:
    - win_test
  gather_facts: false
  become_method: runas
  vars:
    ansible_become_password: "{{ ans_password }}"

  tasks:
    - set_fact:
        beforeCount: "{{ hostvars[inventory_hostname][fileCount] }}"

    - debug:
        var: beforeCount
 
