---
- hosts: aix
  name: Test AIX Command

  tasks:
    - name: Show home info
      debug:
        msg: HOme = {{ ansible_env.HOME }}
  
    - name: Show env for PATH
      debug:
        msg: Path = {{ ansible_env.PATH }}
  
#    - name: Show env for pythonwarnings
      #debug:
      #  msg: PythonWarnings = {{ lookup('env', 'PYTHONWARNINGS') }}
#      shell: "echo $PYTHONWARNINGS"
      #environment:
      #  PYTHONWARNINGS: ignore
      #register: pyreg

    - name: Show env for pythonwarnings
      debug:
        msg: PythonWarnings = {{ lookup('env', 'PYTHONWARNINGS') }}
        #msg: "{{ pyreg.stdout_lines }}"

