---
- block:
  - debug:
      msg: "{{ Update_host_CDB_Server }}- updated /etc/hosts file on CDB Server"

  - name: " update the /etc/hosts file"
    community.windows.win_lineinfile:
      path: 'C:\Windows\System32\drivers\etc\hosts'
      backrefs: yes
      regexp: '^172\.31\.1\.119'
      line: '172.31.12.119'
      state: present
    register: result

  - debug:
      msg: "{{ Update_host_CDB_Server }}- IP address Updated."
    when: result.changed

  - debug:
      msg: "{{ Update_host_CDB_Server }}- IP address not Updated."
    when: not result.changed

  tags:
    - B29
