---
- block:
    - set_fact:
        rec: "{{ select_stat.row[rowNumber].LIB, select_stat.row[rowNumber].OBJ, select_stat.row[rowNumber].DESC }}"

    - set_fact:
        rec1: "{{ rec | replace('(','')| replace(')','') | replace(\"'\",'') | replace(' ','') }}"

    - shell: |
        echo {{rec1}} >> "{{ansPath}}/{{tempFile}}"

  delegate_to: localhost
  tags:
    - PA13a
    - PA13b


