---
- block:
    - block:
      - name: "{{actNo}} - Display library file by running CL DSPFD command in Prod server"
        ibm.power_ibmi.ibmi_cl_command:
          cmd: DSPFD FILE({{fileLibrary}}/{{fileDSP}})
        ignore_errors: yes
        register: crt_lib_result

      - debug:
          var: crt_lib_result

      - set_fact:
          memberCount: "{{ crt_lib_result.stdout | regex_findall('Total number of members \\W+.*:\\s+(\\d+)','\\1') | replace(\"['\",'') | replace(\"']\",'') }}"

      - set_fact:
          memberRecNumber: "{{ crt_lib_result.stdout | regex_findall('(\\w+)\\s+\\d+\\s+\\d+/\\d+/\\d+\\s+\\d+/\\d+/\\d+\\s+\\d+:\\d+:\\d+\\s+(\\d+)','\\1','\\2') }}"

      - name: "{{actNo}} - Publish TLOG record number for Prod server"
        set_fact:
          prodRecord: "The record number for member {{memberRecNumber[item][0]}} in Prod server is {{memberRecNumber[item][1]}}"
        with_items: {0}
        when: memberRecNumber[item] is defined
        delegate_to: localhost

      when: inventory_hostname == prod_ip

    - block:
      - name: "{{actNo}} - Display library file by running CL DSPFD command in DR server"
        ibm.power_ibmi.ibmi_cl_command:
          cmd: DSPFD FILE({{fileLibrary}}/{{fileDSP}})
        ignore_errors: yes
        register: crt_lib_result

      - debug:
          var: crt_lib_result

      - set_fact:
          memberCount: "{{ crt_lib_result.stdout | regex_findall('Total number of members \\W+.*:\\s+(\\d+)','\\1') | replace(\"['\",'') | replace(\"']\",'') }}"

      - set_fact:
          memberRecNumber: "{{ crt_lib_result.stdout | regex_findall('(\\w+)\\s+\\d+\\s+\\d+/\\d+/\\d+\\s+\\d+/\\d+/\\d+\\s+\\d+:\\d+:\\d+\\s+(\\d+)','\\1','\\2') }}"

      - name: "{{actNo}} - Publish TLOG record number for DR server"
        set_fact:
          DRRecord: "The record number for member {{memberRecNumber[item][0]}} in DR server is {{memberRecNumber[item][1]}}"
        with_items: {0}
        when: memberRecNumber[item] is defined
        delegate_to: localhost

      when: inventory_hostname == dr_ip

    - block:
        - set_fact:
            priTLogRec: "{{ hostvars[prod_ip]['prodRecord'] }}"
            drTLogRec: "{{ hostvars[dr_ip]['DRRecord'] }}"
            
        - debug:
            var: priTLogRec

        - debug:
            var: drTLogRec 
    
      delegate_to: localhost    
    
  tags:
    - A28
