---
- block:

    - name: "{{actNo}} - Run MQ Manager check command"
      ibm.power_ibmi.ibmi_cl_command:
        cmd: DSPMQMSTS MQMNAME({{MQM}})
      ignore_errors: yes
      register: crt_lib_result
      
    - debug:
        var: crt_lib_result

    - block:
        - name: "{{actNo}} - Check MQ Manager {{MQM}} running status"
          assert:
            that:
              - "'Queue Manager Status . . . . . :   RUNNING' in crt_lib_result.stdout"
            fail_msg: "MQ Manager {{MQM}} is not running. Please check!"
            success_msg: "MQ Manager {{MQM}} is running"
      when: MQMAction == 'start'

    - block:
        - name: "{{actNo}} - Check MQ Manager {{MQM}} running status"
          assert:
            that:
              - "'Queue Manager Status . . . . . :   RUNNING' not in crt_lib_result.stdout"
            fail_msg: "MQ Manager {{MQM}} is still running. Please check!"
            success_msg: "MQ Manager {{MQM}} is stopped"
      when: MQMAction == 'stop'


  tags:
    - A15

