---
- block:

    - name: "{{actNo}} - Drop temp tables"
      community.postgresql.postgresql_table:
        name: "{{ item }}"
        state: absent
        db: "{{pgDB}}"
        login_host: "{{host}}"
        login_user: "{{DBuser}}"
        login_password: "{{DBpassword}}"
      with_items: "{{ tbl2bCreated }}"
      register: tblDrop

    - debug:
        var: tblDrop

    - name: "{{actNo}} - Create Temp table for Prod Data"
      community.postgresql.postgresql_table:
        name: "{{ item }}"
        columns:
        - "{{tblColumn1}}"
        - "{{tblColumn2}}"
        - "{{tblColumn3}}"
        owner: "{{DBuser}}"
        db: "{{pgDB}}"
        login_host: "{{host}}"
        login_user: "{{DBuser}}"
        login_password: "{{DBpassword}}"
      with_items: "{{ tbl2bCreated }}"
      register: tblCreate

    - debug:
        var: tblCreate

    - name: "{{actNo}} - Load data from file into table from Prod data"
      community.postgresql.postgresql_copy:
        copy_from: "{{ansPath}}/{{tempFileProd}}"
        dst: "{{prodTbl}}"
        options:
          delimiter: ','
          null: 'N'
        db: "{{pgDB}}"
        login_host: "{{host}}"
        login_user: "{{DBuser}}"
        login_password: "{{DBpassword}}"
      register: loadProdStat

    - debug:
        var: loadProdStat

    - name: "{{actNo}} - Load data from file into table from DR data"
      community.postgresql.postgresql_copy:
        copy_from: "{{ansPath}}/{{tempFileDR}}"
        dst: "{{drTbl}}"
        options:
          delimiter: ','
          null: 'N'
        db: "{{pgDB}}"
        login_host: "{{host}}"
        login_user: "{{DBuser}}"
        login_password: "{{DBpassword}}"
      register: loadDRStat

    - debug:
        var: loadDRStat

    - name: "{{actNo}} - Retrieve Prod {{objType}} entr(ies)"
      community.postgresql.postgresql_query:
        db: "{{pgDB}}"
        query: select * from {{prodTbl}};
        login_host: "{{host}}"
        login_user: "{{DBuser}}"
        login_password: "{{DBpassword}}"
      register: dataFromProd

    - name: "{{actNo}} - Retrieve Prod {{objType}} entr(ies)"
      community.postgresql.postgresql_query:
        db: "{{pgDB}}"
        query: select * from {{drTbl}};
        login_host: "{{host}}"
        login_user: "{{DBuser}}"
        login_password: "{{DBpassword}}"
      register: dataFromDR

    - name: "{{actNo}} - Retrieve extra {{objType}} entr(ies) from Prod server(if exist)"
      community.postgresql.postgresql_query:
        db: "{{pgDB}}"
        query: select * from {{prodTbl}} except select * from {{drTbl}};
        login_host: "{{host}}"
        login_user: "{{DBuser}}"
        login_password: "{{DBpassword}}"
      register: extraFromProd

    - debug:
        var: extraFromProd.rowcount

    - name: "{{actNo}} - Retrieve extra {{objType}} entr(ies) from DR server(if exist)"
      community.postgresql.postgresql_query:
        db: "{{pgDB}}"
        query: select * from {{drTbl}} except select * from {{prodTbl}};
        login_host: "{{host}}"
        login_user: "{{DBuser}}"
        login_password: "{{DBpassword}}"
      register: extraFromDR

    - shell: |
        echo "All Prod Data:" > {{ansPath}}/temp/tempdA24

    - shell: |
        echo "{{ 'Member: ' + dataFromProd.query_result[item].member + '; Number of Records: ' + dataFromProd.query_result[item].no_of_records|string + '; Deleted Records: ' + dataFromProd.query_result[item].deleted_records|string}}"  >> {{ansPath}}/temp/tempdA24
      loop: "{{ range(0, (dataFromProd.query_result)| length)|list }}"

    - shell: |
        echo "All DR Data:" >> {{ansPath}}/temp/tempdA24

    - shell: |
        echo "{{ 'Member: ' + dataFromDR.query_result[item].member + '; Number of Records: ' + dataFromDR.query_result[item].no_of_records|string + '; Deleted Records: ' + dataFromDR.query_result[item].deleted_records|string}}"  >> {{ansPath}}/temp/tempdA24
      loop: "{{ range(0, (dataFromDR.query_result)| length)|list }}"

    - shell: |
        cat {{ansPath}}/temp/tempdA24
      register: result1

    - debug:
        msg: "{{actNo}} - All Prod & DR data is as follows:\r{{ result1.stdout }}"

    - block:
        - name: "{{actNo}} - Output the difference between Prod & DR into temp file"
          shell: |
            echo "DR Data:" > {{ansPath}}/temp/tempF2

        - shell: |
            echo "{{ 'Member: ' + extraFromDR.query_result[item].member + '; Number of Records: ' + extraFromDR.query_result[item].no_of_records|string + '; Deleted Records: ' + extraFromDR.query_result[item].deleted_records|string}}"  >> {{ansPath}}/temp/tempF2
          loop: "{{ range(0, (extraFromDR.query_result)| length)|list }}"

        - shell: |
            echo "Prod Data:" >> {{ansPath}}/temp/tempF2

        - shell: |
            echo "{{ 'Member: ' + extraFromProd.query_result[item].member + '; Number of Records: ' + extraFromProd.query_result[item].no_of_records|string + '; Deleted Records: ' + extraFromProd.query_result[item].deleted_records|string}}"  >> {{ansPath}}/temp/tempF2
          loop: "{{ range(0, (extraFromProd.query_result)| length)|list }}"

        - name: "{{actNo}} - The difference between PROD & DR as follows:"
          shell: |
            cat {{ansPath}}/temp/tempF2
          register: result

        - debug:
            msg: "{{actNo}} - Difference between PROD & DR as follows:\r{{ result.stdout }}"

      when:
        - extraFromProd.rowcount|int > 0
        - extraFromDR.rowcount|int > 0

    - block:
        - debug: 
            msg: "{{actNo}} - The data between Prod and DR is matched."

      when:
        - extraFromProd.rowcount|int == 0
        - extraFromDR.rowcount|int == 0

  become: yes
  become_user: postgres
  tags: 
    - A24c
