---
- block:
    - name: "{{actNo}} - Drop temp tables"
      shell: cat {{tempFileProd}}
      register: prodResult

    - shell: cat {{tempFileDR}}
      register: drResult

    - name: "{{actNo}} - Compare Prod and DR Total"
      assert:
        that:
          - prodResult.stdout == drResult.stdout
        fail_msg: "Card type total between Prod & DR environments is different. Please check!"
        success_msg: "Card type total between Prod & DR environments matched."


  delegate_to: localhost
  tags: 
    - A23c
