---
- block:

    - name: "{{actNo}} - Spool out Subsystem info"
      ibm.power_ibmi.ibmi_cl_command:
        cmd: WRKSBS
      register: crt_lib_result
      
    - debug:
        var: crt_lib_result

    - name: "{{actNo}} - copy the output to a local file"
      copy:
        content: "{{ crt_lib_result.stdout }}"
        dest: "{{ansPath}}/{{tempFile}}"
      delegate_to: localhost

    - name: "{{actNo}} - Clean up data in temp file"
      shell: |
        cat "{{ansPath}}/{{tempFile}}" | grep -v "Subsystem" | grep -v "E N D  O F  L I S T I N G" | awk '{print $1}' > {{ansPath}}/tempF
        mv {{ansPath}}/tempF "{{ansPath}}/{{tempFile}}"
      register: cleanUpStat
      delegate_to: localhost
  
    - debug:
        var: cleanUpStat

  tags:
    - PA14a
    - PA14b

