---

- include_tasks: retrieveLib.yml
  vars:
    library: QGPL
    tblName: ANS_PA12_P
    actNo: PA12
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodLib
  when: inventory_hostname in prod_ip
  tags: [PA12a]

- include_tasks: retrieveLib.yml
  vars:
    library: QGPL
    tblName: ANS_PA12_D
    actNo: PA12
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drLib
  when: inventory_hostname in dr_ip
  tags: [PA12b]

- include_tasks: compareProdnDR_2TblCols.yml
  vars:
    actNo: PA12
    objType: library
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodLib
    tempFileDR: temp/drLib
    tbl2bCreated:
      - cbs_prod_lib_data
      - cbs_dr_lib_data
    tblColumn1: obj_name varchar(30)
    tblColumn2: obj_desc varchar(80)
    prodTbl: cbs_prod_lib_data
    drTbl: cbs_dr_lib_data
  when: inventory_hostname in ans_pg_DB
  tags: [PA12c]

- include_tasks: retrieveBOQ.yml
  vars:
    library: QGPL
    appLibrary: S3DATBIMB2
    tblName: ASI_PA13_P
    actNo: PA13
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodBOQ
  when: inventory_hostname in prod_ip
  tags: [PA13a]

- include_tasks: retrieveBOQ.yml
  vars:
    library: QGPL
    appLibrary: S3DATBIMB2
    tblName: ASI_PA13_D
    actNo: PA13
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drBOQ
  when: inventory_hostname in dr_ip
  tags: [PA13b]

- include_tasks: compareProdnDR_3TblCols.yml
  vars:
    actNo: PA13
    objType: branchOutQueue
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodBOQ
    tempFileDR: temp/drBOQ
    tbl2bCreated:
      - cbs_prod_boq
      - cbs_dr_boq
    tblColumn1: lib_name varchar(20)
    tblColumn2: obj_name varchar(20)
    tblColumn3: obj_desc varchar(30)
    prodTbl: cbs_prod_boq
    drTbl: cbs_dr_boq
  when: inventory_hostname in ans_pg_DB
  tags: [PA13c]

- include_tasks: compareSubSystems.yml
  vars:
    actNo: PA14
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodSBS
  when: inventory_hostname in prod_ip
  tags: [PA14a]

- include_tasks: compareSubSystems.yml
  vars:
    actNo: PA14
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drSBS
  when: inventory_hostname in dr_ip
  tags: [PA14b]

- include_tasks: compareProdnDR.yml
  vars:
    actNo: PA14
    objType: subsystem
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodSBS
    tempFileDR: temp/drSBS
    tbl2bCreated:
      - cbs_prod_subsystem
      - cbs_dr_subsystem
    tblColumn: subsystem varchar(30)
    prodTbl: cbs_prod_subsystem
    drTbl: cbs_dr_subsystem
  when: inventory_hostname in ans_pg_DB
  tags: [PA14c]

- include_tasks: retrieveSBSClass.yml
  vars:
    library: QGPL
    tblName: ASI_PA15_P
    actNo: PA15
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodSBSClass
  when: inventory_hostname in prod_ip
  tags: [PA15a]

- include_tasks: retrieveSBSClass.yml
  vars:
    library: QGPL
    tblName: ASI_PA15_D
    actNo: PA15
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drSBSClass
  when: inventory_hostname in dr_ip
  tags: [PA15b]

- include_tasks: compareProdnDR_2TblCols.yml
  vars:
    actNo: PA15
    objType: library
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodSBSClass
    tempFileDR: temp/drSBSClass
    tbl2bCreated:
      - cbs_prod_sbsclass_data
      - cbs_dr_sbsclass_data
    tblColumn1: obj_name varchar(30)
    tblColumn2: obj_desc varchar(80)
    prodTbl: cbs_prod_sbsclass_data
    drTbl: cbs_dr_sbsclass_data
  when: inventory_hostname in ans_pg_DB
  tags: [PA15c]

- include_tasks: compareJobScheduler.yml
  vars:
    actNo: PA16
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodJobScheduler
  when: inventory_hostname in prod_ip
  tags: [PA16a]

- include_tasks: compareJobScheduler.yml
  vars:
    actNo: PA16
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drJobScheduler
  when: inventory_hostname in dr_ip
  tags: [PA16b]

- include_tasks: compareProdnDR_4TblCols.yml
  vars:
    actNo: PA16
    objType: JobScheduler
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodJobScheduler
    tempFileDR: temp/drJobScheduler
    tbl2bCreated:
      - cbs_prod_job_scheduler
      - cbs_dr_job_scheduler
    tblColumn1: job_name varchar(30)
    tblColumn2: entry_no varchar(20)
    tblColumn3: scheduled_time varchar(20)
    tblColumn4: scheduled_by varchar(30)
    prodTbl: cbs_prod_job_scheduler
    drTbl: cbs_dr_job_scheduler
  when: inventory_hostname in ans_pg_DB
  tags: [PA16c]

- include_tasks: holdOrReleaseJobScheduler.yml
  vars:
    actNo: PA17
    jobname: PNSS9014C
    entryNum: 000494
    action: Hold
    actionMsg: held
    command: HLDJOBSCDE
  when: inventory_hostname in prod_ip
  tags: [PA17]

- include_tasks: holdOrReleaseJobScheduler.yml
  vars:
    actNo: PA17
    jobname: PNSS9014C
    entryNum: 000494
    action: Release
    actionMsg: released
    command: RLSJOBSCDE
  when: inventory_hostname in prod_ip
  tags: [PA17x]


#####################################

- include_tasks: stopOrStartSBS_individual.yml
  vars:
    actNo: A11
    SBSAct: STOP
    SBSLib: QGPL
    SBSName: PBIEBSSBS
  when: inventory_hostname in prod_ip
  tags: [A11]


- include_tasks: holdOrReleaseJobScheduler.yml
  vars:
    actNo: A14
    jobname: SMS_ALERTS
    entryNum: "000665"
    action: Hold
    actionMsg: held
    command: HLDJOBSCDE
  when: inventory_hostname in prod_ip
  tags: [A14a]

- include_tasks: holdOrReleaseJobScheduler.yml
  vars:
    actNo: A14
    jobname: SMS_24ALRT
    entryNum: "000069"
    action: Hold
    actionMsg: held
    command: HLDJOBSCDE
  when: inventory_hostname in prod_ip
  tags: [A14b]

- include_tasks: stopOrStartMQM.yml
  vars:
    actNo: A15
    MQMAct: stop
    command: ENDMQM
    MQM: CBS.CCRIS
  when: inventory_hostname in prod_ip
  tags: [A15]

- include_tasks: stopOrStartSBSs.yml
  vars:
    actNo: A16
    sheetName: A16
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/SBSCheckStatus
    SBSAct: STOP
  when: inventory_hostname in prod_ip
  tags: [A16]

- include_tasks: stopOrStartFTP.yml
  vars:
    actNo: A17
    action: stopped
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/ftpF
    grepMsg: "FTP server not active"
  when: inventory_hostname in prod_ip
  tags: [A17]

- include_tasks: compareLibFiles.yml
  vars:
    actNo: A20
    sheetName: A20
    ansPath: /install/CBS/cbs_uat
    tempfile: temp/prodFileRecDetails
  when: inventory_hostname in prod_ip
  tags: [A20a]

- include_tasks: compareLibFiles.yml
  vars:
    actNo: A20
    sheetName: A20
    ansPath: /install/CBS/cbs_uat
    tempfile: temp/drFileRecDetails
  when: inventory_hostname in dr_ip
  tags: [A20b]

- include_tasks: compareProdnDR_3TblColsA20.yml
  vars:
    actNo: A20
    objType: fileinLibrary
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodFileRecDetails
    tempFileDR: temp/drFileRecDetails
    tbl2bCreated:
      - cbs_prod_file_in_library
      - cbs_dr_file_in_library
    tblColumn1: library_file varchar(30)
    tblColumn2: member varchar(20)
    tblColumn3: records int
    prodTbl: cbs_prod_file_in_library
    drTbl: cbs_dr_file_in_library
  when: inventory_hostname in ans_pg_DB
  tags: [A20c]

- include_tasks: runQuerySummary.yml
  vars:
    actNo: A21
    library: QGPL
    tblName: A21Q_P
    libQryName: LIBRECOVER/QDREBCRDM
    sql2run: "select coalesce(nullif(ECCSTS,''),'TOTAL') || ',' || ECCARD05 AS \"CARDSTATUSANDNUMBER\" from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodQueryResultA21
  when: inventory_hostname in prod_ip
  tags: [A21a]

- include_tasks: runQuerySummary.yml
  vars:
    actNo: A21
    library: QGPL
    tblName: A21Q_D
    libQryName: LIBRECOVER/QDREBCRDM
    sql2run: "select coalesce(nullif(ECCSTS,''),'TOTAL') || ',' || ECCARD05 AS \"CARDSTATUSANDNUMBER\" from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drQueryResultA21
  when: inventory_hostname in dr_ip
  tags: [A21b]

- include_tasks: compareProdnDR_2TblCols.yml
  vars:
    actNo: A21
    objType: cardTypeAndNumberofCard
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodQueryResultA21
    tempFileDR: temp/drQueryResultA21
    tbl2bCreated:
      - cbs_prod_queryoutput_a21
      - cbs_dr_queryoutput_a21
    tblColumn1: card_type varchar(30)
    tblColumn2: numberof_card_type INT
    prodTbl: cbs_prod_queryoutput_a21
    drTbl: cbs_dr_queryoutput_a21
  when: inventory_hostname in ans_pg_DB
  tags: [A21c]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/memberVar.yml"
  tags: [A22z]

- include_tasks: runQuery.yml
  # Make sure to run together with A22z 
  vars:
    actNo: A22
    library: QGPL
    tblName: A22Q_P
    #    libQryName: LIBRECOVER/QDREBSTLG QRYFILE((DTNEBS/EBSTLG {{fileMember}})) 
    libQryName: LIBRECOVER/QDREBSTLG QRYFILE((S3DTNEBS/EBSTLG {{fileMember}})) 
    sql2run: "select E01RRN from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodQueryResultA22
  when: inventory_hostname in prod_ip
  tags: [A22a]

- include_tasks: runQuery.yml
  # Make sure to run together with A22z 
  vars:
    actNo: A22
    library: QGPL
    tblName: A22Q_D
    libQryName: LIBRECOVER/QDREBSTLG QRYFILE((S3DTNEBS/EBSTLG {{fileMember}})) 
    sql2run: "select E01RRN from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drQueryResultA22
  when: inventory_hostname in dr_ip
  tags: [A22b]

- include_tasks: compareProdnDR.yml
  vars:
    actNo: A22
    objType: queryOutput
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodQueryResultA22
    tempFileDR: temp/drQueryResultA22
    tbl2bCreated:
      - cbs_prod_queryoutput_a22
      - cbs_dr_queryoutput_a22
    tblColumn: E01RRN varchar(30)
    prodTbl: cbs_prod_queryoutput_a22
    drTbl: cbs_dr_queryoutput_a22
  when: inventory_hostname in ans_pg_DB
  tags: [A22c]

- include_tasks: runQuerySummary.yml
  vars:
    actNo: A23
    library: QGPL
    tblName: A23Q_P
    libQryName: LIBRECOVER/QDREBACNO
    sql2run: "select EACTYP05 from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodQueryResultA23
  when: inventory_hostname in prod_ip
  tags: [A23a]

- include_tasks: runQuerySummary.yml
  vars:
    actNo: A23
    library: QGPL
    tblName: A23Q_D
    libQryName: LIBRECOVER/QDREBACNO
    sql2run: "select EACTYP05 from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drQueryResultA23
  when: inventory_hostname in dr_ip
  tags: [A23b]

- include_tasks: compareProdnDR_cardTotal.yml
  vars:
    actNo: A23
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodQueryResultA23
    tempFileDR: temp/drQueryResultA23
  tags: [A23c]

- include_tasks: callProgram.yml
  vars:
    actNo: A24
    library: QGPL
    tblName: A24Q_P
    PgmName: LIBRECOVER/RPPLIST
    sql2run: "select MLNAME || ',' || MLNRCD || ',' || MLNDTR from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodQueryResultA24
  when: inventory_hostname in prod_ip
  tags: [A24a]

- include_tasks: callProgram.yml
  vars:
    actNo: A24
    library: QGPL
    tblName: A24Q_D
    PgmName: LIBRECOVER/RPPLIST
    sql2run: "select MLNAME || ',' || MLNRCD || ',' || MLNDTR from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drQueryResultA24
  when: inventory_hostname in dr_ip
  tags: [A24b]
  
- include_tasks: compareProdnDR_3TblColsA24.yml
  vars:
    actNo: A24
    objType: ProgramObject
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodQueryResultA24
    tempFileDR: temp/drQueryResultA24
    tbl2bCreated:
      - cbs_prod_queryoutput_a24
      - cbs_dr_queryoutput_a24
    tblColumn1: member varchar(30)
    tblColumn2: no_of_records INT
    tblColumn3: deleted_records INT
    prodTbl: cbs_prod_queryoutput_a24
    drTbl: cbs_dr_queryoutput_a24
  when: inventory_hostname in ans_pg_DB
  tags: [A24c]

- include_tasks: testCLCommand.yml
  when: inventory_hostname in dr_ip
  tags: [TEST]

