---
- block:
    - name: "{{actNo}} - Drop table {{tblName}} if exists"
      ibm.power_ibmi.ibmi_sql_execute:
        sql: "drop table {{library}}.{{tblName}}"
      ignore_errors: yes
      register: dropTBLState

    - debug:
        var: dropTBLState

    - name: "{{actNo}} - Display all subsystem class"
      ibm.power_ibmi.ibmi_cl_command:
        cmd: QSYS/DSPOBJD OBJ(*ALL) OBJTYPE(*CLS) OUTPUT(*OUTFILE) OUTFILE({{library}}/{{tblName}})

    - name: "{{actNo}} - retrieve result from above from DB2 table {{tblName}}"
      ibm.power_ibmi.ibmi_sql_query:
        sql: "select CONCAT(CONCAT(ODOBNM,','), coalesce(nullif(ODOBTX,''),'NULL')) AS \"RECORD\" from {{library}}.{{tblName}}"
      register: select_stat

    - name: "{{actNo}} - Copy the output from above to a local temp file"
      copy:
        content: "{{ select_stat.row | to_yaml }}"
        dest: "{{ansPath}}/{{tempFile}}"
      delegate_to: localhost

    - name: "{{actNo}} - clean up entries in {{tempFile}}"
      shell: |
        cat {{ansPath}}/{{tempFile}} | sed 's/  //g' | sed 's/- {//g' | sed "s/RECORD: '//g" | sed 's/ ,/,/g' | sed "s/'//g" | sed 's/}//g' > {{ansPath}}/tempF
        mv {{ansPath}}/tempF {{ansPath}}/{{tempFile}} 
      register: cleanupState
      delegate_to: localhost
     
    - debug:
        var: cleanupState

  tags:
    - PA15a
    - PA15b

