---
- block:
    - name: "{{actNo}} - Drop table {{tblName}} if exists"
      ibm.power_ibmi.ibmi_sql_execute:
        sql: "drop table {{library}}.{{tblName}}"
      ignore_errors: yes
      register: dropTBLState

    - debug:
        var: dropTBLState

    - name: "{{actNo}} - Display all libraries"
      ibm.power_ibmi.ibmi_cl_command:
        cmd: QSYS/DSPOBJD OBJ(*ALL) OBJTYPE(*LIB) OUTPUT(*OUTFILE) OUTFILE({{library}}/{{tblName}})

    - name: "{{actNo}} - retrieve result from above from DB2 table {{tblName}}"
      ibm.power_ibmi.ibmi_sql_query:
        sql: "select CONCAT(CONCAT(ODOBNM,','), coalesce(nullif(ODOBTX,''),'NULL')) AS \"RECORD\" from QGPL.ANS_PA12_P"
      register: select_stat

    - name: "{{actNo}} - Copy the output from above to a local temp file"
      copy:
        content: "{{ select_stat.row | to_yaml }}"
        dest: "{{ansPath}}/{{tempFile}}"
      delegate_to: localhost

    - name: "{{actNo}} - Clean up data in temp file"
      shell: |
        cat {{ansPath}}/{{tempFile}} | sed 's/  //g' | sed 's/- {//g' | sed "s/RECORD: '//g" | sed 's/ ,/,/g' | sed "s/'//g" | sed 's/}//g' > {{ansPath}}/tempF 
        mv {{ansPath}}/tempF "{{ansPath}}/{{tempFile}}"
      register: cleanUpStat
      delegate_to: localhost

    - debug:
        var: cleanUpStat

  tags:
    - PA12a
    - PA12b
