---
  - block:
      - name: "Query servers' entries in Excel file named {{excelFileName}}"
        open_excel:
          src: "{{excelFileName}}"
          sheet_name: "{{sheetName}}"
          index_by_name: false
          op: "r"
          read_range: "{{ {'start_row': 1, 'start_col': 1, 'end_row': '{{rowInExcel}}', 'end_col': 2} }}"
        register: result

      - debug:
          var: result

    delegate_to: localhost
    tags:
      - A16
      - A49
      - B36
      - B66
      - B67

  - block:
      - name: "{{actNo}} - {{SBSAct}} Subsystem"
        include_tasks: stopOrStartSBS.yml
        vars:
          rowNumber: "{{ outer_item }}"
        with_items: {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20}
        loop_control:
          loop_var: outer_item

      - pause:
          seconds: 10

      - name: "Delete temp file"
        file:
          path: "{{ansPath}}/{{tempFile}}"
          state: absent
        delegate_to: localhost

      - name: "{{ actNo }} - Check Subsystem status"
        include_tasks: checkSBSStatus.yml
        vars:
          SBSAction: "{{SBSAct}}"
          rowNumber: "{{ outer_item }}"
        with_items: {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20}
        loop_control:
          loop_var: outer_item

      - debug: 
          msg: "The subsystem {{SBSAct}} status is:\r{{lookup('file', '{{ansPath}}/{{tempFile}}') }}"
        become: yes
        become: root
        delegate_to: localhost

    tags:
      - A16
      - A49
      - B36
      - B66
      - B67
