---
# Run the below tasks only on the database
- include_tasks: update_db.yml
  vars:
    update_db_act_no: P11
    tbl_update: "update BANKISLAMMBUAT1.tb_abnf_promotion_master set auth_status='A' where content_id='890' and screen_id='DownTime';"
    update_check: "select auth_status from BANKISLAMMBUAT1.tb_abnf_promotion_master where content_id='890' and screen_id='DownTime';"
    expected_op: "A"
  when: inventory_hostname==prod_db_server_ip
  tags:
    - P11


- include_tasks: "{{ role_path }}/../commons/tasks/cache_refresh.yml"
  vars:
    cache_refresh_act_no: P11.1
  when: inventory_hostname in primary_cache_refresh_server_ip
  tags:
    - P11.1

- block:
  - include_tasks: stop_apache_servers.yml
  vars:
    stop_apache_act_no: P12
  become: yes
  become_user: root
  when: inventory_hostname in DR_apache_server_ips
  tags:
    - P12

- include_tasks: stop_jboss_modules.yml
  vars:
    stop_JBoss_module_act_no: P13
  when: inventory_hostname==DR_jboss_server_ip
  tags:
    - P13

- include_tasks: stop_jboss_instances.yml
  vars:
    stop_JBoss_act_no: P14
  when: inventory_hostname in DR_jboss_instances_ip
  tags:
    - P14
     
- block:
  - include_tasks: update_hosts_file.yml
  vars:
    update_etc_hosts_act_no: P16
  become: yes
  become_user: root
  when: inventory_hostname in primary_jboss_instances_ip
  tags:
    - P16
