---
- block:
  - debug:
      msg: "{{ stop_apache_act_no }}- Bringing down apache servers"

  - stat:
      path: "{{ apache_server_bin_path }}"
    register: apache_server_path

  - fail:
      msg: "{{ stop_apache_act_no }}- Apache server bin path {{ apache_server_bin_path }}  doesn't exist."
    when: not apache_server_path.stat.exists

  - name: "{{ stop_apache_act_no }}- ApacheServer: Checking the status of apache server"
    shell: ps -ef | grep httpd
    ignore_errors: yes
    changed_when: false
    register: service_apache_status

  # Let's not do anything if the apache server is not running at all
  - name: "{{ stop_apache_act_no }}- ApacheServer: Skipping the restart as the server is already in stopped state."
    block:
      - debug:
          msg: "{{ stop_apache_act_no }}- Apache server is not running. Skipping"
    when: not "httpd -k start" in service_apache_status.stdout

  # Stop the apache server , if the server is in running state

  - name: "{{ stop_apache_act_no }}- ApacheServer: Restarting the apache server."
    block:
      - name: "{{ stop_apache_act_no }}- ApacheServer: Stopping the apache server."
        command:
          chdir: '{{ apache_server_bin_path }}'
          cmd: bash -l ./apachectl stop
        ignore_errors: yes
        register: run_result
    when: '"httpd -k start" in service_apache_status.stdout'

  - pause:
      seconds: "{{ pause_duration }}"

  #again check the status of apache server and make sure the service is stopped or else fail the task
  - name: "{{ stop_apache_act_no }}- ApacheServer: Checking the status of apache server"
    shell: ps -ef | grep httpd
    changed_when: false
    ignore_errors: yes
    register: service_apache_status

  - name: "{{ stop_apache_act_no }}- ApacheServer: Reporting the  status of Apache. "
    fail:
      msg: "{{ stop_apache_act_no }}- Service apache2 is still running."
    when: '"httpd -k start" in service_apache_status.stdout'

  - debug:
      msg: "{{ stop_apache_act_no }}- Apache servers is successfully stopped."

  tags:
    - P12
    - B2
    - A1
