---
- block:
  - debug:
      msg: "{{ update_etc_hosts_act_no }}- Creating hosts entries and updating /etc/hosts file"

  - name: "{{ update_etc_hosts_act_no }}- Delete {{ ep_dr_file_path }} if it exists"
    file:
      path: "{{ ep_dr_file_path }}"
      state: absent
    ignore_errors: yes

  - name: "{{ update_etc_hosts_act_no }}- Creating {{ ep_dr_file_path }} directory if it does not exist"
    file:
      path: "{{ ep_dr_dir_path }}"
      state: directory

  - name: "{{ update_etc_hosts_act_no }}- Creating {{ ep_dr_file_path }}"
    file: 
      path: "{{ ep_dr_file_path }}"
      state: touch

  - name: "{{ update_etc_hosts_act_no }}- Copying the contents to file {{ ep_dr_file_path }} "
    copy:
      content: "{{ item }}"
      dest: "{{ ep_dr_file_path }}"
    loop: "{{ ep_dr_file_contents }}"

  - name: "{{ update_etc_hosts_act_no }}- Backup the existing /etc/hosts"
    copy:
      src: /etc/hosts
      dest: /etc/hosts.{{lookup('pipe','date +%Y-%m-%d')}}
      remote_src: yes
    register: result

  - name: "{{ update_etc_hosts_act_no }}- Delete old entries in /etc/hosts"
    lineinfile:
      dest: /etc/hosts
      state: absent
      regexp: "{{ item }}"
    loop: "{{ line_to_delete_in_hosts_file }}"
    ignore_errors: yes
        

  - name: "{{ update_etc_hosts_act_no }}- Copying the contents to /etc/hosts file"
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      create: yes
    loop: "{{ ep_dr_file_contents }}"

  tags:
    - P16
