# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

alias sibs='cd /var/gitlab-repos/affin_dr_automation/SIBS_nonprod'
alias amax='cd /var/gitlab-repos/affin_dr_automation/Affinmax_nonprod'
alias ccmt='cd /var/gitlab-repos/affin_ccm_tracker/CCMTracker'
alias winpatch='cd /var/gitlab-repos/affin_winupdates_automation/WinPatchMgmt'

source /usr/share/git-core/contrib/completion/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export PS1='[\u@\h \W$(declare -F __git_ps1 &>/dev/null && __git_ps1 " (%s)")]\$ '

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
