---
- block:
  - debug:
      msg: "{{ bring_down_tomcat_services }}- restart the tomcat service"

  - name: "{{ bring_down_tomcat_services }}-Restart the Tomcat service"
    ansible.windows.win_service:
      name: Tomcat7
      state: restarted
    register: tomcat_services
    ignore_errors: yes

  - fail:
      msg: "Tomcat failed to start!"
    when: tomcat_services.failed == true
     
  - debug:
      msg: "{{ bring_down_tomcat_services }}- Restarted Tomcat service."
      
  tags:
    - A23   
    - A41   
