---
- block:
  - debug:
      msg: "{{ stop_CBS_Jompay }}- Stop the CBS JomPay Listner"

  - stat:
      path: "{{ Stop_CBS_JomPAY_Listener_script }}"
    register: stop_CBS_JomPAY_path 
    
  - fail:
      msg: "{{ stop_CBS_Jompay }}- CBS JomPAY Listener path {{ Stop_CBS_JomPAY_Listener_script }}  doesn't exist."
    when: not stop_CBS_JomPAY_path.stat.exists

  - name: "{{ stop_CBS_Jompay }}- Stop the CBS JomPAY Listener"
    command: " {{ Stop_CBS_JomPAY_Listener_script }} "
    register: stop_CBS_Jompay_Listener

  - debug:
      var: stop_CBS_Jompay_Listener.stdout

  - pause:
      seconds: "{{pause_duration}}"

  - name: "{{ stop_CBS_Jompay }}- IBConnectorListenerCbs: Checking the status of IBConnectorListenerCbs"
    shell: 'netstat -an | grep "8900" | grep "LISTEN" | wc -l'
    ignore_errors: yes
    changed_when: false
    register: CBS_JomPAY_Listener_status

  - debug:
      var: CBS_JomPAY_Listener_status.stdout | trim

  - name: "{{ stop_CBS_Jompay }}- IBConnectorListenerCbs: Reporting the status of CBS_JomPAY Listener. "
    fail:
      msg: "{{ stop_CBS_Jompay}}- CBS_JomPAY Listener is running."
    when: CBS_JomPAY_Listener_status.stdout | trim != '0'  

  - debug:
      msg: "{{ stop_CBS_Jompay }}- CBS JomPAY Listener successfully stopped."

  become: yes
  tags:
    - A19
    - B9

