---
- hosts: win
  gather_facts: false
  become_method: runas

  vars:
    ansible_become_password: "{{ ans_password }}"

  tasks:
    - include_role:
        name: checkpoint-4
      tags: [B2]

  any_errors_fatal: true
