---
- block:
    - include_tasks: Check_ip.yml
      when: inventory_hostname in WAS_DR_ips
      tags: [B1.1]

    - include_tasks: Stop_WAS_DRC.yml
      when: inventory_hostname in WAS_DR_ips
      tags: [B1.2]

    - include_tasks: Start_WAS_DRC.yml
      when: inventory_hostname in WAS_DR_ips
      tags: [B1.3] 

    - include_tasks: verify_WAS_DRC.yml
      when: inventory_hostname in WAS_DR_ips
      tags: [B1.4]   