---
- block:
  - debug:
      msg: "{{ start_CBS_Jompay }}- Start the CBS JomPay Listner"

  - stat:
      path: "{{ Start_CBS_JomPAY_Listener_script }}"
    register: start_CBS_JomPAY_path 
    
  - fail:
      msg: "{{ start_CBS_Jompay }}- CBS JomPAY Listener path {{ Start_CBS_JomPAY_Listener_script }}  doesn't exist."
    when: not start_CBS_JomPAY_path.stat.exists
    
  - name: "{{ start_CBS_Jompay }}- Start the CBS JomPAY Listener"
    command: " {{ Start_CBS_JomPAY_Listener_script }} "
    register: start_CBS_Jompay_Listener
    ignore_errors: yes
 
  - debug:
      var: start_CBS_Jompay_Listener.stdout

  - pause:
      seconds: "{{pause_duration}}"

  - name: "{{ start_CBS_Jompay }}- IBConnectorListenerCbs: Checking the status of IBConnectorListenerCbs"
    shell: 'netstat -an | grep "8900" | grep "LISTEN" | wc -l'
    ignore_errors: yes
    changed_when: false
    register: CBS_JomPAY_Listener_status

  - debug:
      var: CBS_JomPAY_Listener_status

  - name: "{{ start_CBS_Jompay }}- IBConnectorListenerCbs: Reporting the status of IBConnectorListenerCbs"
    fail:
      msg: "{{ start_CBS_Jompay }}- Service CBS JomPay is not running."
    when: CBS_JomPAY_Listener_status.stdout | trim == '0'

  - debug:
      msg: "{{ start_CBS_Jompay }}- CBS JomPAY Listener successfully started."

  become: yes
  tags:
    - A38
    - B25

