---
- block:
  - debug:
      msg: "Start the WAS DRC Manager/Node/Server"

  - name: WAS DRC is start Manager...
    command: chdir={{ manager }} {{ item }}
    with_items:
    - ./stopManager.sh
    register: Manager_start_result  
  - debug:
      var: Manager_start_result.stdout

  - name: WAS DRC is start node...
    command: chdir={{ server }} {{ item }}
    with_items:
    - ./startNode.sh
    - ./startServer.sh server1
    register: Server_start_result
  
  - debug:
      var: Server_start_result.stdout

  - debug:
      msg: "WAS DRC has started successfully "
  
  tags:
    - B1.3