---
- block:
  - debug:
      msg: "stop the WAS DRC Manager/Node/Server"

  - name: WAS DRC is stop Server
    expect:
        command: bash -c "{{ server }}stopServer.sh server1"
        responses:
                "Username": "{{ username }}"
                "Password": "{{ password }}"
        
    register: Server_stop_result
  
  - debug:
      var: Server_stop_result.stdout

  - name: WAS DRC is stop node...
    expect:
        command: bash -c "{{ node }}stopNode.sh "
        responses:
                "Username": "{{ username }}"
                "Password": "{{ password }}"
        
    register: node_stop_result
  
  - debug:
      var: node_stop_result.stdout


  - name: WAS DRC is stop Manager...
    expect:
        command: bash -c "{{ manager }}stopManager.sh"
        responses:
                "Username": "{{ username }}"
                "Password": "{{ password }}"
        
    register: Manager_stop_result  

  - debug:
      var: Manager_stop_result.stdout


  - debug:
      msg: "WAS DRC has stopped successfully "
  
  tags:
    - B1.2