---
- block:
  - debug:
      msg: "Stop the WAS DRC"
  

  - name: WAS DRC is stop Serve and node...
    shell: |
       cd /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/
       spawn ./stopServer.sh server1 ansible_user='{{   }}
       expect "username:"
       send -- "{{ username }}\n"
       expect "password:"
       send -- "{{ password }}\n"
       expect eof
#    args:
#      executable: /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/
    register: server_stop_result

  - name: WAS DRC is stop Node...
    command: chdir=/opt/IBM/WebSphere/AppServer/profiles/Dmgr01/bin/ {{ item }}
    with_items:
    - ./stopNode.sh
    register: Node_stop_result          


  
  - debug:
      var: Server_stop_result

  - name: WAS DRC is stop Manager...
    command: chdir=/opt/IBM/WebSphere/AppServer/profiles/Dmgr01/bin/ {{ item }}
    with_items:
    - ./stopManager.sh
    register: Manager_stop_result  


  - debug:
      var: Manager_stop_result

#  - name: "WAS_DRC Stop process faild "
#    fail:
#      msg: "not able to stop QMLPPIB"
#    when: Manager_stop_result.stdout | trim == '0'

  - debug:
      msg: "WAS DRC has stop successfully "
  
  tags:
    - B1.2