---

- include_tasks: "{{ role_path }}/../pre_activities/tasks/DBMirrorSwitchOver.yml"
  vars:
    DBMirroring: "B9"
    SQLServerInstance: "??"
    DBName: "master"
    DB2BSwitchOver: "??"
  when: inventory_hostname in dr_db_ip
  tags: [B9]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B10"
    svc_name: "TBD"
    action: "stop"
  when: inventory_hostname in app_ips
  tags: [B10]

- include_tasks: "{{role_path}}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B12-B13"
    svc_name: "TBD"
    action: "start"
  when: inventory_hostname in app_ips
  tags: [B12-B13]

- include_tasks: "{{role_path}}/../pre_activities/tasks/DBMirrorCheckSyncAndMirrorRole.yml"
  vars:
    DBMirroring: "B13"
    SQLServerInstance: "??"
    DBName: "master"
    checkSync: "SYNCHRONIZED"
    mirrorRole: "PRINCIPAL"
    DB2BSwitchOver: "??"
  when: inventory_hostname in db_ip
  tags: [B13]

