---

- debug:
    msg: "{{ disable_cron_job_IB_App }}- Disable the Cron Job in IB App Servers."
  tags:
    - A20.05
    - A20
    - B10
    
- debug:
    msg: "{{ disable_cron_job_IB_App }}- Check if the crontab has already been disabled"
  tags:
    - A20.05
    - A20
    - B10
    
- name: "{{ disable_cron_job_IB_App }}- Query crontab -l status"
  shell: crontab -l | grep -v "^#" | wc -l
  register: cron_stat
  tags:
    - A20.05
    - A20
    - B10

- set_fact:
   cron_disabled: false           
  tags:
    - A20.05
    - A20
    - B10
            
- set_fact:
    cron_disabled: true
  when: cron_stat.stdout | trim == '0'
  tags:
    - A20.05
    - A20
    - B10
        
- debug:
    var: cron_stat.stdout | trim
  tags:
    - A20.05
    - A20
    - B10

- debug:
    var: cron_disabled
  tags:
    - A20.05
    - A20
    - B10
            
- block:
  - name: "{{disable_cron_job_IB_App}}- Backup the cron job "
    shell:
      cmd: |
        rm /var/spool/cron/crontabs/root.bak.*;
        /usr/bin/crontab -l > /var/spool/cron/crontabs/root.bak.`date +%y_%m_%d`
    register: result
    tags:
      - A20.1

  - debug:
      msg: "{{ disable_cron_job_IB_App }}- cronjob backup successfully"

  - name: "{{disable_cron_job_IB_App}}- Comment cron job"
    shell: "cat /var/spool/cron/crontabs/root | sed 's/^/#/g' > /tmp/1; cp /tmp/1 /var/spool/cron/crontabs/root"
    tags:
      - A20.1

  - name: "{{disable_cron_job_IB_App}}- Restart cron job"
    shell:
      cmd: ps -ef | grep cron
    register: cmd
    tags:
      - A20.2

  - set_fact:
      pid_2b_delete: "{{ item }}"
    with_items: "{{ cmd.stdout_lines }}"
    when: not item | regex_search('.*' + 'pts' + '.*')
    tags:
      - A20.2

  - set_fact:
      pid_2b_delete: "{{ pid_2b_delete.split()[1] }}"
    tags:
      - A20.2

  - name: "{{ disable_cron_job_IB_App }}- Killing the process id {{ pid_2b_delete }}"
    shell:
      cmd: "kill -9 {{ pid_2b_delete }}"
    tags:
      - A20.2

  - debug:
      msg: "{{ disable_cron_job_IB_App }}- cronjob disabled successfully"
    tags:
      - A20.2

  when: cron_disabled == false
  tags:
    - A20
    - B10

