---

- include_tasks: "{{ role_path }}/../pre_activities/tasks/holdOrReleaseJobScheduler.yml"
  vars:
    actNo: B1
    jobname: PNSS9014C
    entryNum: 000808
#    entryNum: 000494
    action: Hold
    actionMsg: held
    command: HLDJOBSCDE
  when: inventory_hostname in dr_ip
  tags: [B1]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/holdOrReleaseJobScheduler.yml"
  vars:
    actNo: B33
    jobname: SMS_ALERTS
    entryNum: "000665"
    action: Hold
    actionMsg: held
    command: HLDJOBSCDE
  when: inventory_hostname in dr_ip
  tags: [B33a]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/holdOrReleaseJobScheduler.yml"
  vars:
    actNo: B33
    jobname: SMS_24ALRT
    entryNum: 000069
    action: Hold
    actionMsg: held
    command: HLDJOBSCDE
  when: inventory_hostname in dr_ip
  tags: [B33b]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartSBS_individual.yml"
  vars:
    actNo: B34
    SBSAct: STOP
    SBSLib: QGPL
    SBSName: PBIEBSTSBS
  when: inventory_hostname in dr_ip
  tags: [B34a]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartSBS_individual.yml"
  vars:
    actNo: B34
    SBSAct: STOP
    SBSLib: QGPL
    SBSName: PBIEBSSBS
  when: inventory_hostname in dr_ip
  tags: [B34b]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartMQM.yml"
  vars:
    actNo: B35
    MQMAct: stop
    command: ENDMQM
    MQM: CBS.CCRIS
  when: inventory_hostname in dr_ip
  tags: [B35]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartSBSs.yml"
  vars:
    actNo: B36
    sheetName: B36
    SBSAct: STOP
  when: inventory_hostname in dr_ip
  tags: [B36]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartFTP.yml"
  vars:
    actNo: B37
    action: stopped
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/ftpF
    grepMsg: "FTP server not active"
  when: inventory_hostname in dr_ip
  tags: [B37]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/compareLibFiles.yml"
  vars:
    actNo: B40
    sheetName: B40
    ansPath: /install/CBS/cbs_uat
    tempfile: temp/prodFileRecDetails
  when: inventory_hostname in prod_ip
  tags: [B40a]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/compareLibFiles.yml"
  vars:
    actNo: B40
    sheetName: B40
    ansPath: /install/CBS/cbs_uat
    tempfile: temp/drFileRecDetails
  when: inventory_hostname in dr_ip
  tags: [B40b]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/compareProdnDR_3TblColsA20.yml"
  vars:
    actNo: B40
    objType: fileinLibrary
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodFileRecDetails
    tempFileDR: temp/drFileRecDetails
    tbl2bCreated:
      - cbs_prod_file_in_library
      - cbs_dr_file_in_library
    tblColumn1: library_file varchar(30)
    tblColumn2: member varchar(20)
    tblColumn3: records int
    prodTbl: cbs_prod_file_in_library
    drTbl: cbs_dr_file_in_library
  when: inventory_hostname in ans_pg_DB
  tags: [B40c]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/runQuerySummary.yml"
  vars:
    actNo: B41
    library: QGPL
    tblName: B41Q_P
    libQryName: LIBRECOVER/QDREBCRDM
    sql2run: "select coalesce(nullif(ECCSTS,''),'TOTAL') || ',' || ECCARD05 AS \"CARDSTATUSANDNUMBER\" from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodQueryResultB41
  when: inventory_hostname in prod_ip
  tags: [B41a]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/runQuerySummary.yml"
  vars:
    actNo: B41
    library: QGPL
    tblName: B41Q_D
    libQryName: LIBRECOVER/QDREBCRDM
    sql2run: "select coalesce(nullif(ECCSTS,''),'TOTAL') || ',' || ECCARD05 AS \"CARDSTATUSANDNUMBER\" from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drQueryResultB41
  when: inventory_hostname in dr_ip
  tags: [B41b]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/compareProdnDR_2TblCols.yml"
  vars:
    actNo: B41
    objType: cardTypeAndNumberofCard
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodQueryResultB41
    tempFileDR: temp/drQueryResultB41
    tbl2bCreated:
      - cbs_prod_queryoutput_b41
      - cbs_dr_queryoutput_b41
    tblColumn1: card_type varchar(30)
    tblColumn2: numberof_card_type INT
    prodTbl: cbs_prod_queryoutput_b41
    drTbl: cbs_dr_queryoutput_b41
  when: inventory_hostname in ans_pg_DB
  tags: [B41c]


- include_tasks: "{{ role_path }}/../pre_activities/tasks/memberVar.yml"
  tags: [B42z]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/runQuery.yml"
  # Make sure to run together with B42z
  vars:
    actNo: B42
    library: QGPL
    tblName: B42Q_P
    #    libQryName: LIBRECOVER/QDREBSTLG QRYFILE((DTNEBS/EBSTLG MP20171203))
    libQryName: LIBRECOVER/QDREBSTLG QRYFILE((S3DTNEBS/EBSTLG {{fileMember}}))
    sql2run: "select E01RRN from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodQueryResultB42
  when: inventory_hostname in prod_ip
  tags: [B42a]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/runQuery.yml"
  # Make sure to run together with B42z
  vars:
    actNo: B42
    library: QGPL
    tblName: B42Q_D
    libQryName: LIBRECOVER/QDREBSTLG QRYFILE((S3DTNEBS/EBSTLG MP20171203))
    sql2run: "select E01RRN from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drQueryResultB42
  when: inventory_hostname in dr_ip
  tags: [B42b]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/compareProdnDR.yml"
  vars:
    actNo: B42
    objType: queryOutput
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodQueryResultB42
    tempFileDR: temp/drQueryResultB42
    tbl2bCreated:
      - cbs_prod_queryoutput_b42
      - cbs_dr_queryoutput_b42
    tblColumn: E01RRN varchar(30)
    prodTbl: cbs_prod_queryoutput_b42
    drTbl: cbs_dr_queryoutput_b42
  when: inventory_hostname in ans_pg_DB
  tags: [B42c]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/runQuerySummary.yml"
  vars:
    actNo: B43
    library: QGPL
    tblName: B43Q_P
    libQryName: LIBRECOVER/QDREBACNO
    sql2run: "select EACTYP05 from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodQueryResultB43
  when: inventory_hostname in prod_ip
  tags: [B43a]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/runQuerySummary.yml"
  vars:
    actNo: B43
    library: QGPL
    tblName: B43Q_D
    libQryName: LIBRECOVER/QDREBACNO
    sql2run: "select EACTYP05 from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drQueryResultB43
  when: inventory_hostname in dr_ip
  tags: [B43b]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/compareProdnDR_cardTotal.yml"
  vars:
    actNo: B43
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodQueryResultB43
    tempFileDR: temp/drQueryResultB43
  tags: [B43c]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/callProgram.yml"
  vars:
    actNo: B44
    library: QGPL
    tblName: B44Q_P
    PgmName: LIBRECOVER/RPPLIST
    sql2run: "select MLNAME || ',' || MLNRCD || ',' || MLNDTR from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/prodQueryResultB44
  when: inventory_hostname in prod_ip
  tags: [B44a]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/callProgram.yml"
  vars:
    actNo: B44
    library: QGPL
    tblName: B44Q_D
    PgmName: LIBRECOVER/RPPLIST
    sql2run: "select MLNAME || ',' || MLNRCD || ',' || MLNDTR from {{library}}.{{tblName}}"
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/drQueryResultB44
  when: inventory_hostname in dr_ip
  tags: [B44b]
  
- include_tasks: "{{ role_path }}/../pre_activities/tasks/compareProdnDR_3TblColsA24.yml"
  vars:
    actNo: B44
    objType: ProgramObject
    ansPath: /install/CBS/cbs_uat
    tempFileProd: temp/prodQueryResultB44
    tempFileDR: temp/drQueryResultB44
    tbl2bCreated:
      - cbs_prod_queryoutput_b44
      - cbs_dr_queryoutput_b44
    tblColumn1: member varchar(30)
    tblColumn2: no_of_records INT
    tblColumn3: deleted_records INT
    prodTbl: cbs_prod_queryoutput_b44
    drTbl: cbs_dr_queryoutput_b44
  when: inventory_hostname in ans_pg_DB
  tags: [B44c]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartSBSs.yml"
  vars:
   actNo: B66
   SBSAct: START
   sheetName: B66
  when: inventory_hostname in prod_ip
  tags: [B66]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartSBSs.yml"
  vars:
   actNo: B67
   SBSAct: START
   sheetName: B67
  when: inventory_hostname in prod_ip
  tags: [B67]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/submitJob.yml"
  vars:
    actNo: B69
    command: SBMJOB CMD(CALL PGM(SSSCPF) PARM('DQSSSCPF')) JOB(SSSCPF) JOBQ(QGPL/QBATCH) USER(BIADMSCD)
    jobName: SSSCPF
  when: inventory_hostname in prod_ip
  tags: [B69]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartMQM.yml"
  vars:
    actNo: B70
    MQMAct: start
    command: STRMQM
    MQM: CBS.CCRIS
  when: inventory_hostname in prod_ip
  tags: [B70]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartFTP.yml"
  vars:
    actNo: B73
    action: started
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/ftpF
    grepMsg: "FTP server starting"
  when: inventory_hostname in prod_ip
  tags: [B73a]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopOrStartSSH.yml"
  vars:
    actNo: B73
    action: started
    ansPath: /install/CBS/cbs_uat
    tempFile: temp/sshF
    grepMsg: "SSHD server starting"
  when: inventory_hostname in prod_ip
  tags: [B73b]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/submitJob.yml"
  vars:
    actNo: B83
    command: SBMJOB CMD(CALL PGM(SS9014C)) JOB(PNSS9014C) JOBD(U2ENVRPP/U2RPPBJBD) INLLIBL(*JOBD) LOG(*JOBD *JOBD *SECLVL) LOGCLPGM(*YES)
    jobName: PNSS9014C
  when: inventory_hostname in dr_ip
  tags: [B83]
