---
- block:
    - block:
        - name: "{{actNo}} - Check Windows version"
          ansible.windows.win_shell: |
            systeminfo /fo csv | ConvertFrom-Csv | select OS*, Hotfix* | Format-List
          register: result

        - set_fact:
            osVersionProd: "{{ result.stdout | regex_search('OS Version\\s+: (.*)\\s{2,}','\\1') }}"
            
        - set_fact:
            hotfixesProd: "{{ result.stdout | regex_search('(Hotfix[(]s[)]\\s+:(.*)[.]).*','\\1') }}"
                                     
      when: inventory_hostname == prod_app_ips
      
    - block:
        - name: "{{actNo}} - Check Windows version"
          ansible.windows.win_shell: |
            systeminfo /fo csv | ConvertFrom-Csv | select OS*, Hotfix* | Format-List
          register: result1

        - set_fact:
            osVersionDR: "{{ result1.stdout | regex_search('OS Version\\s+: (.*)\\s{2,}','\\1') }}"
            
        - set_fact:
            hotfixesDR: "{{ result1.stdout | regex_search('Hotfix[(]s[)]\\s+: (.*)\\s{2,}','\\1') }}"

      when: inventory_hostname == dr_app_ips

    - block:
        - name: "{{actNo}} - Compare Windows version between 2 environments"
          debug:
            var: hostvars[prod_app_ips]['osVersionProd']
            
        - debug:
            var: hostvars[dr_app_ips]['osVersionDR']
      
        - assert:
            that:
              - hostvars[prod_app_ips]['osVersionProd'] == hostvars[dr_app_ips]['osVersionDR']
            success_msg: "{{actNo}} - Windows versions matched between Prod server {{prod_app_ips}} and DR server {{dr_app_ips}}"
            fail_msg: "{{actNo}} - Windows versions are not matched between Prod server {{prod_app_ips}} and DR server {{dr_app_ips}}. Please check!"


        - name: "{{actNo}} - Compare Windows patch level between 2 environments"
          debug:
            var: hostvars[prod_app_ips]['hotfixesProd']
            
        - debug:
            var: hostvars[dr_app_ips]['hotfixesDR']
      
        - assert:
            that:
              - hostvars[prod_app_ips]['hotfixesProd'] == hostvars[dr_app_ips]['hotfixesDR']
            success_msg: "{{actNo}} - Windows patch level matched between Prod server {{prod_app_ips}} and DR server {{dr_app_ips}}"
            fail_msg: "{{actNo}} - Windows patch levels are not matched between Prod server {{prod_app_ips}} and DR server {{dr_app_ips}}. Please check!"
          ignore_errors: yes          
          
      delegate_to: localhost  
      when: inventory_hostname == dr_app_ips     
      
  tags:
    - P5
    - P6

