- block:

    - name: "{{actNo}} - Display running {{serviceName}} processes"
      win_shell: "tasklist /v | findstr \"{{ serviceName }}\" | findstr \"{{ currentUser }}\""
      register: runningProcess
      ignore_errors: yes

    - debug:
        var: runningProcess

    - set_fact:
        process2bKilled: no

    - set_fact:
        process2bKilled: yes
      when: runningProcess.stdout|length != 0

    - debug:
        var: process2bKilled

    - block:
        - name: "{{actNo}} - Kill running {{serviceName}} processes"
          win_shell: Stop-Process -Name "{{ serviceName }}" -Force
          register: killedProcess
          ignore_errors: yes
 
        - debug:
            var: killedProcess

        - pause:
            seconds: 5

      when: process2bKilled

    - name: "{{actNo}} - Check if process {{serviceName}} still running"
      win_shell: "tasklist /v | findstr \"{{ serviceName }}\" | findstr \"{{ currentUser }}\""
      register: checkProcessState
      ignore_errors: yes

    - block:
      - assert:
          that:
            - checkProcessState.stdout | length == 0
          success_msg: "{{actNo}} - process {{serviceName}} is/are not running in server {{inventory_hostname}}"
          fail_msg: "{{actNo}} - process {{serviceName}} is/are still running in server {{inventory_hostname}}. Please check!"
        ignore_errors: yes

  tags:
    - P13
    - P14

