---

- include_tasks: preConnTests.yml
  vars:
    actNo: P3
    excelFileName: eSpick_PreConnTest.xlsx
    sheetName: Sheet1
    rowInExcel: 4
  when: inventory_hostname == ans_control
  tags: [P3]

- include_tasks: checkWindowsVersion.yml
  vars:
    actNo: P5-P6
    #  when: inventory_hostname in prod_app_ips
  tags: [P5,P6]

- include_tasks: checkDriveUsages.yml
  vars:
    actNo: P7
    drives:
    - C
    - D
  when: inventory_hostname == prod_app_ips
  tags: [P7]

- include_tasks: verifyFileChksum.yml
  vars:
    actNo: P8
    prodFilepath: "D:\\output\\BPS.xml"
    drFilepath: "D:\\output\\uattakafulbillpres.bankislam.com.my.cer"
  tags: [P8]

- include_tasks: DBMirrorCheckSyncAndMirrorRole.yml
  vars:
    DBMirroring: "P11"
    SQLServerInstance: "??"
    DBName: "master"
    checkSync: "SYNCHRONIZED"
    mirrorRole: "PRINCIPAL"
    DB2BSwitchOver: "??"
  when: inventory_hostname in db_ip
  tags: [P11]

- include_tasks: killWindowsProcesses.yml
  vars:
    actNo: P13
    currentUser: "BIMBSupport"
    serviceName: 
    - javaw
  when: inventory_hostname in dr_GWC_Client
  tags: [P13]

- include_tasks: killWindowsProcesses.yml
  vars:
    actNo: P14
    currentUser: "BIMBSupport"
    serviceNames: 
    - rmiregistry
    - javaw
    - java
  when: inventory_hostname in dr_app_ips
  tags: [P14]

- include_tasks: DBMirrorCheckSyncAndMirrorRole.yml
  vars:
    DBMirroring: "P18"
    SQLServerInstance: "??"
    DBName: "master"
    checkSync: "SYNCHRONIZED"
    mirrorRole: "PRINCIPAL"
    DB2BSwitchOver: "??"
  when: inventory_hostname in db_ip
  tags: [P18]

- include_tasks: killWindowsProcesses.yml
  vars:
    actNo: P14
    currentUser: "BIMBSupport"
    serviceNames:
    - rmiregistry
    - javaw
    - java
  when: inventory_hostname in prod_app_ips
  tags: [P14]

