---

- block:
    - set_fact:
        fileFullName: '{{ result.sheet_index_0[rowNumber] }}'

    - set_fact:
        sourceIP: "{{ fileFullName.col_1 }}"
        destIP: "{{ fileFullName.col_2 }}"
        port: "{{ fileFullName.col_3 }}"

  delegate_to: localhost
  tags:
    - P3

- block:
    - name: "{{actNo}} - Login to sourceIP, then perform remote test"
      win_wait_for:
        host: "{{ destIP }}"
        port: "{{ port }}"
        state: started
        delay: 0
        timeout: 3
      delegate_to: "{{ sourceIP }}"
      ignore_errors: yes
      register: testResult
 
    - debug:
        var: testResult
  when: 
    - sourceIP != 'None'

  tags:
    - P3
