---
- block:
    - name: "{{actNo}} - Query servers and ports info in Excel file name {{excelFileName}}"
      open_excel:
        src: "{{excelFileName}}"
        sheet_name: "{{sheetName}}"
        index_by_name: false
        op: "r"
        read_range: "{{ {'start_row': 1, 'start_col': 1, 'end_row': '{{rowInExcel}}', 'end_col': 3} }}"
      register: result

    - debug:
        var: result.sheet_index_0 | length

    - name: "{{actNo}} - Test remote connection from designated hosts"
      include_tasks: preConnTest.yml
      vars:
        rowNumber: "{{ outer_item }}"
      with_items: { 0,1 }
      #      loop: "{{ range(0, (result.sheet_index_0)| length)|list }}"
      loop_control:
        loop_var: outer_item

  delegate_to: localhost
  tags:
    - P3
