---

- block:
    - block:
        - set_fact:
            serv: '{{ result.sheet_index_0[rowNumber] }}'
          
        - set_fact:
            servIP: "{{ serv.col_1 }}"
            servPort: "{{ serv.col_2 }}"

        - name: "Perform testing to connect to {{servIP}}"
          shell: timeout 2s curl -v telnet://{{servIP}}:{{servPort}} 
          register: connTestResult
          failed_when: false

        - set_fact:
            ConnTstResult: "Connection to {{servIP}}:{{servPort}} is OK"
          when: (connTestResult.stderr | regex_search("Connected to") | default('global', boolean=True)) in connTestResult.stderr

        - set_fact:
            ConnTstResult: "Connection to {{servIP}}:{{servPort}} is not OK!"
          when: (connTestResult.stderr | regex_search("Connected to") | default('global', boolean=True)) not in connTestResult.stderr

        - name: "Write result to a temp file"
          lineinfile:
            path: /tmp/ConnectTest
            line: "{{ConnTstResult}}"
            create: yes

      when: 
        - result.sheet_index_0[rowNumber] is defined
        - result.sheet_index_0[rowNumber].col_1 != "None"
  become: yes
  tags:
    - sshkey
