---
## Run this Playbook to test connectivity from Ansible Controller to remote hosts
## make sure to use the correct variable: excelFileName, excelSheetNameSSHKey, excelSheetNameUnixLinuxConnTest, rowInExcel,
## ansibleController, remote_user

- hosts:
    - ansibleController
  gather_facts: no

  tasks:
    - block:
        - name: "Query servers' entries in Excel file named {{excelFileName}}"
          open_excel:
            src: "{{excelFileName}}"
            sheet_name: "{{excelSheetNameUnixLinuxConnTest}}"
            index_by_name: false
            op: "r"
            read_range: "{{ {'start_row': 1, 'start_col': 1, 'end_row': '{{rowInExcel}}', 'end_col': 2} }}"
          register: result

        - name: "Delete temp file"
          file:
            path: /tmp/ConnectTest
            state: absent

        - name: "Test Remote hosts' connection"
          include_tasks: connfromAnsControlToRemoteServ.yaml
          vars:
            rowNumber: "{{ outer_item }}"
          with_items:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
          loop_control:
            loop_var: outer_item

        - name: "Remote hosts connection test result"
          debug:
            msg: "Please check file /tmp/ConnectTest on the connection test result from Ansible Controller"

      become: yes
      delegate_to: 127.0.0.1
      tags:
        - sshkey

