---

## Run this playbook to delete Ansible Controller's SSH key in remote hosts
## make sure to use the correct variable: excelFileName, excelSheetNameSSHKey, excelSheetNameUnixLinuxConnTest, rowInExcel,
## ansibleController, remote_user

- hosts:
    - ansibleController
  gather_facts: no

  vars:
    controller_hostname: "{{ lookup('pipe', 'hostname') }}"

  tasks:
    - block:
        - name: "Query servers' entries in Excel file named {{excelFileName}}"
          open_excel:
            src: "{{excelFileName}}"
            sheet_name: "{{excelSheetNameSSHKey}}"
            index_by_name: false
            op: "r"
            read_range: "{{ {'start_row': 1, 'start_col': 1, 'end_row': '{{rowInExcel}}', 'end_col': 2} }}"
          register: result

        - name: "Delete temp file"
          file:
            path: /tmp/SSHKeyDelete
            state: absent

        - name: "Delete SSH keys from remote servers"
          include_tasks: deleteSSHKeyFromServer.yaml
          with_items: result.rowNumber
          when:
            - result.sheet_index_0[rowNumber] is defined
            - result.sheet_index_0[rowNumber].col_1 != "None"


        - name: "SSH Key deletion result"
          debug:
            msg: "Please check file /tmp/SSHKeyDelete on the SSH Key deletion result"

      become: yes
      delegate_to: 127.0.0.1
      tags:
        - sshkeyDelete

