---
- block:
    - debug:
        msg: "{{ start_IB_Report_Quartz }}- Start IB Report Quartz in IB App servers"

    - stat:
        path: "{{ Start_IB_Report_Quartz_script }}"
      register: Start_Report_Quartz_script

    - fail:
        msg: "{{ start_IB_Report_Quartz }}- Start IB Report Quartz path {{ Start_IB_Report_Quartz_script }}  doesn't exist."
      when: not Start_Report_Quartz_script.stat.exists


    - name: " {{ start_IB_Report_Quartz }}-Start the IB Report Quartz"
      command: ksh " {{ Start_IB_Report_Quartz_script }} "
      register: start_result
      ignore_errors: yes

    - debug:
          var: start_result.stdout

    - pause:
        seconds: "{{pause_duration}}"

    - set_fact:
        start_stat: true
        
    - set_fact:
        start_stat: false
      when: '"IBG Return Notification Quartz is already running" not in start_result.stdout'
      
    - block:   
        - fail:
            msg: "IB Report Quartz cannot be started!"
          when: '"IBG Return Notification Quartz started" not in start_result.stdout'
      when: start_stat == false    
        
        
    - debug:
        msg: "{{ start_IB_Report_Quartz  }}- IB Report Quartz successfully started."

  become: yes
  tags:
    - B27

