apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
    namespace: sonar
    labels:
        name: sonatypestorage 
spec:
    storageClassName: default 
    capacity:
        storage: 50Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: "/bitnami/postgresql"
