---

- hosts:
    - all
  gather_facts: false

  tasks:
   - include_role:
       name: checkpointing-4
     tags: [B14,B14a,B15,B16,B17,B18,B19,B20,B21,B23,B24,B25,B26,B27,B29,B30,B30a]
  
  any_errors_fatal: true


