---

- hosts:
    - all
  gather_facts: false

  tasks:
   - include_role:
       name: go-no-go
     tags: [A1,A2,A3,A4,A5,A6,A9,A9a,A10,A11,A12,A13,A14,A15,A16,A17,A18,A19,A20,A20.05,A20.1,A20.2,A21,A22,A23]

  any_errors_fatal: true
