---
# Run the below tasks only on the database
- include_tasks: update_db.yml
  vars:
    - tbl_update: "update BANKISLAMMBUAT1.tb_abnf_promotion_master set auth_status='A' where content_id='890' and screen_id='DownTime';"
    - update_check: "select auth_status from BANKISLAMMBUAT1.tb_abnf_promotion_master where content_id='890' and screen_id='DownTime';"
    - expected_op: "A"
  when: inventory_hostname==prod_db_server_ip
  tags:
   - P11


- include_tasks: "{{ role_path }}/../commons/tasks/cache_refresh.yml"
  when: inventory_hostname in primary_cache_refresh_server_ip
  tags:
     - P11.1

- block:
  - include_tasks: stop_apache_servers.yml
  become: yes
  become_user: root
  when: inventory_hostname in primary_apache_server_ips
  tags:
     - P12

- include_tasks: stop_jboss_modules.yml
  when: inventory_hostname==primary_jboss_server_ip
  tags:
     - P13

- include_tasks: stop_jboss_instances.yml
  when: inventory_hostname in primary_jboss_server_ip
  tags:
     - P14
     
- block:
  - include_tasks: update_hosts_file.yml
  become: yes
  become_user: root
  when: inventory_hostname in primary_jboss_server_ip
  tags:
     - P16
