# Block run handlers in error handling  
---
- name: Attempt and graceful roll back demo
  block:
    - debug:
        msg: 'I execute normally'
        changed_when: yes
        notify: run me even after an error
    - command: /bin/false
  rescue:
    - name: make sure all handlers run
      meta: flush_handlers
  handlers: 
     - name: run me even after an error
       debug:
         msg: 'This handler runs even on error'
