---

- hosts:
    - all
  gather_facts: false
  become_method: runas
  vars:
    ansible_become_password: "{{ ans_password }}"

  tasks:
   - include_role:
       name: swing_over_DR
     tags: [P8,P9,P10,P12,P14,P15,P16,P17,A2,A5a,A5.1a,A5.1b,A5.1c,A5c,A5.2a,A5.2b,A5.2c]
  
  any_errors_fatal: true


