---

#verify if the stop banking script exist or not
#st stands for status
#st_bank_script_path refers to the status of bank script path
- stat:
    path: "{{ jboss_stop_banking_script }}"
  register: st_bank_script_path

- fail:
    msg: "Stop banking script {{ jboss_stop_banking_script }} doesn't exist"
  when: not st_bank_script_path.stat.exists

#verify if the stop reporting script exist or not
- stat:
    path: "{{ jboss_stop_reporting_script }}"
  register: st_reporting_script_path

- fail:
    msg: "Stop reporting script {{ jboss_stop_reporting_script }} doesn't exist"
  when: not st_reporting_script_path.stat.exists

#verify if the stop admin script exist or not
- stat:
    path: "{{ jboss_stop_admin_script }}"
  register: st_admin_script_path

- fail:
    msg: "Stop banking script {{ jboss_stop_admin_script }} doesn't exist"
  when: not st_admin_script_path.stat.exists

- stat:
    path: "{{ jboss_eap_path }}"
  register: st_eap_path

- fail:
    msg: "Jbos EAP path {{ jboss_eap_path }} doesn't exist"
  when: not st_eap_path.stat.exists

- name: "Stopping banking module"
  shell:
    cmd: "{{ jboss_stop_banking_script }}"

- name: "Stopping reporting module"
  shell:
    cmd: "{{ jboss_stop_reporting_script }}"

- name: "Stopping admin module"
  shell:
    cmd: "{{ jboss_stop_admin_script }}"

#Verify if the banking, admin and reporting processes are stopped, by retrieving the PIDs
- name: "Check if banking module is stopped"
  pids:
    name: Banking
    #mod is acronym for module. Example admin_mod_status refers to admin module status
  register: bank_mod_status

- name: "Check if reporting module is stopped"
  pids:
    name: Reporting
    #mod is acronym for module. Example admin_mod_status refers to admin module status
  register: report_mod_status

- name: "Check if admin module is stopped"
  pids:
    name: Admin
    #mod is acronym for module. Example admin_mod_status refers to admin module status
  register: admin_mod_status

- fail:
    msg: "Banking module is not stopped. Please check."
  when: not bank_mod_status.pids|length == 0

- fail:
    msg: "Reporting module is not stopped. Please check."
  when: not report_mod_status.pids|length == 0

- fail:
    msg: "Admin module is not stopped. Please check."
  when: not admin_mod_status.pids|length == 0

- debug:
    msg: "Banking, reporting and admin modules are successfully stopped."
