---
- stat:
    path: "{{ jboss_eap_path }}"
  register: st_jboss_eap

- fail:
    msg: "Path {{ jboss_eap_path }} doesn't exist"
  when: not st_jboss_eap.stat.exists

- name: "Stopping JBoss instance"
  shell:
    chdir: "{{ jboss_eap_path }}"
    cmd: stopjb.sh

#Verify if the jboss is stopped or not
- name: "Verifying if Jboss instance is stopped"
  pids:
    name: jboss
  register: jboss_status

- fail:
    msg: "Jboss instance is not stopped. Please check."
  when: not jboss_status.pids|length == 0

- debug:
    msg: "Jboss instance is successfully stopped."