---
- block:
  - debug:
      msg: "This is activity no. {{ chk_conn_act_no }}"

  - name: "{{ chk_conn_act_no }}- CheckConnectivity: Running connectivity script"
    shell:
      cmd: "{{ connectivity_script_file }}"
    changed_when: false
    register: connectivity_status

  - debug:
      var: connectivity_status

  - set_fact:
      conn_status: []

  - set_fact:
      conn_status: "{{ conn_status }} + [ '{{ item }}' ]"
    with_items: "{{ connectivity_status.stdout_lines }}"
    when: item | regex_search("(.*)failed(.*)$")

  - block:
    - name: "{{ chk_conn_act_no }}- CheckConnectivity: Dumping the connectivity status"
      debug:
        var: conn_status

    - fail:
        msg: "{{ chk_conn_act_no }}- Connectivity test failed. Please check the failed connectivity test as above."

    when: not conn_status == ""

  - debug:
      msg: "{{ chk_conn_act_no }}- Connectivity test is successfull"

  tags:
    - P7
