---
#for failover source_site will be prod and target_site will be dr
- block:
    - block:
        - name: Checking Sun Cluster resource status
          include_tasks: ../../commons/tasks/run_db_command.yml
          vars:
            command: clrs show -v drcms-db-rs
            expected_outputs:
              - 'Dataguard_role: PRIMARY'
          tags:
            - A7_1
            - A7
        - name: change Sun Cluster resource status to IN_TRANSITION
          include_tasks: run_db_command.yml
          vars:
            command: clrs set -p Dataguard_role=IN_TRANSITION drcms-db-rs
            expected_outputs:
              - 'Dataguard_role: IN_TRANSITION'
          tags:
            - A7_2
            - A7

        - name: Access Oracle DG Broker and check status
          include_tasks: run_db_command.yml
          vars:
            command: su - oracle; dgmgrl /; show configuration;
            expected_outputs:
              - 'SUCCESS'
            tags:
              - A7_3
              - A7

        - name: Validate primary database status
          include_tasks: run_db_command.yml
          vars:
            command: su - oracle; dgmgrl /; validate database mbprd;
            expected_outputs:
              - "Database Role: Primary database"
              - "Ready for Switchover: Yes"
            tags:
              - A7_4
              - A7

        - name: Validate physical standby database status
          include_tasks: run_db_command.yml
          vars:
            command: su - oracle; dgmgrl /; validate database mbprd_dr;
            expected_outputs:
              - "Database Role: Physical Standby database"
              - "Ready for Switchover: Yes"
            tags:
              - A7_5
              - A7

        - name: Switchover the DB
          include_tasks: run_db_command.yml
          vars:
            command: su - oracle; dgmgrl /; switchover to mbprd_dr;
            expected_outputs:
              - "SUCCESSFUL"
          tags:
            - A7_6
            - A7

        - name: change Sun Cluster resource status to STANDBY
          include_tasks: run_db_command.yml
          vars:
            command: clrs set -p Dataguard_role=STANDBY -p Standby_mode=PHYSICAL drcms-db-rs
          tags:
            - A7_7
            - A7

        - name: Checking Sun Cluster resource status
          include_tasks: ../../commons/tasks/run_db_command.yml
          vars:
            command: clrs show -v drcms-db-rs
            expected_outputs:
              - 'Dataguard_role: STANDBY'
          tags:
            - A7_7
            - A7
      when: inventory_hostname=={{ source_site }}_db_server_ip
      tags:
        - A7
        - A7_1
        - A7_2
        - A7_3
        - A7_4
        - A7_5
        - A7_6
        - A7_7

    - block:
       ## Login to DR DB server
       - name: change Sun Cluster resource status to Primary
         include_tasks: ../../commons/tasks/run_db_command.yml
         vars:
           command: clrs set -p Dataguard_role=PRIMAR drcms-db-rs
         tags:
           - A7_8
           - A7

       - name: Checking Sun Cluster resource status
           include_tasks: ../../commons/tasks/run_db_command.yml
           vars:
             command: clrs show -v drcms-db-rs
             expected_outputs:
               - 'Dataguard_role: PRIMARY'
           tags:
             - A7_8
             - A7
      when: inventory_hostname=={{ target_site }}_db_server_ip
      tags:
        - A7
        - A7_8

  tags:
     - A7
     - A7_1
     - A7_2
     - A7_3
     - A7_4
     - A7_5
     - A7_6
     - A7_7
     - A7_8
