---
- include_tasks: "{{ role_path }}/../stop_services/tasks/update_db.yml"
  vars:
    - tbl_update: "update BANKISLAMMBUAT1.tb_abnf_promotion_master set auth_status='U' where content_id='890' and screen_id='DownTime';"
    - update_check: "select auth_status from BANKISLAMMBUAT1.tb_abnf_promotion_master where content_id='890' and screen_id='DownTime';"
    - expected_op: "U"
  when: inventory_hostname==prod_db_server_ip
  tags:
    - B23

- include_tasks: "{{ role_path }}/../commons/tasks/cache_refresh.yml"
  when: inventory_hostname in primary_cache_refresh_server_ip
  tags:
    - B23.1
