---
- hosts: localhost
  gather_facts: false

  vars:
    portinfo: "{{ lookup('file', filename ) }}"

  tasks:
    - name: Ensure filename is defined
      fail:
        msg: "Usage: ansible-playbook testconn.yml -e 'filename=<your_filename_here>'"
      when: filename is not defined

    - set_fact:
        ipPortList: "{{ ipPortList | default([]) + [item | regex_search('(.*):(.*)','\\1','\\2')] }}"
      loop: "{{ portinfo.split('\n') | list }}"

    - name: Test port connectivity
      wait_for:
        host: "{{ item.0 }}"
        port: "{{ item.1 }}"
        state: started
        delay: 0
        timeout: 3
      ignore_errors: yes
      register: portout
      loop: "{{ ipPortList }}"
        
    - name: Empty previous results
      copy:
        dest: ./failed_ports_{{ filename }}
        content: ''
        force: yes

    - name: Save failed connections to file
      lineinfile:
        path: ./failed_ports_{{ filename }}
        line: "Access to {{ item.item.0 }} port {{ item.item.1 }} is not successful. Please check."
        insertbefore: BOF
      no_log: true
      when: item.msg is defined and 'Timeout' in item.msg
      loop: "{{ portout.results }}"
        
    - name: Empty previous results
      copy:
        dest: ./success_ports_{{ filename }}
        content: ''
        force: yes

    - name: Write results to file
      lineinfile:
        path: ./success_ports_{{ filename }}
        line: "Access to {{ item.item.0 }} port {{ item.item.1 }} is successful."
        insertbefore: BOF
      no_log: true
      when: item.msg is not defined
      loop: "{{ portout.results }}"
