---
- block:

    - set_fact: 
        dayMinus: 0
      when: dayMinus is not defined

    - win_shell: (Get-date).AddDays({{dayMinus}}).ToString('dd-MM-yyyy')
      register: result

    - debug:
        var: result.stdout
   
    - set_fact:
        servDate: "{{result.stdout | trim}}"

    - win_shell: (Get-date).AddDays({{dayMinus}}).ToString('yyyy-MM-dd')
      register: result2

    - debug:
        var: result2.stdout

    - set_fact:
        servDateRev: "{{result2.stdout | trim}}"

    - win_shell: (Get-date).AddDays({{dayMinus}}).ToString('dd/MM/yyyy')
      register: result3

    - debug:
        var: result3.stdout

    - set_fact:
        servDatePYZ: "{{result3.stdout | trim}}"


  tags:
    - A5a
    - B13a
