---

- hosts: all
  gather_facts: false
  become_method: runas
  vars:
    ansible_become_password: "{{ ans_password }}"

  tasks:
   - include_role:
       name: swing_back_prod
     tags: [B9]
  
  any_errors_fatal: true


