---
- hosts: localhost

  vars:
    teststr: ABC/DATA-'[1]'


  tasks:
  - debug:
      var: teststr

  - set_fact:
      newstr: "{{ teststr | regex_replace(\"(.*-)'\\[(.+)\\]'\", '\\1\\2') }}"

  - debug:
      var: newstr
