---

- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
   - include_role:
       name: swing_back_prod
     tags: [B1,B33a,B33b,B35,B36,B37,B40a,B40b,B41a,B42a,B43a,B41b,B42b,B43b]
  
#  any_errors_fatal: true


