---

- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
   - include_role:
       name: swing_over_DR
     tags: [A28,A49,A51,A58a,A58b,A65,A94]
  
#  any_errors_fatal: true


