---
- block:
  - debug:
      msg: "{{ dr_enable_cron_job }}- Enable the Cron Job in IB App Servers."
  tags:
    - A39
    - B26

- block:
  - name: "{{dr_enable_cron_job}}- Backup the cron job "
    shell:
      cmd: |
        rm /var/spool/cron/crontabs/root.bak.*;
        /usr/bin/crontab -l > /var/spool/cron/crontabs/root.bak.{{lookup('pipe','date +%Y-%m-%dT%H.%M.%S')}}
    register: result
    tags:
      - A39.1

  - debug:
      msg: "{{ dr_enable_cron_job }}- cronjob backup successfully"

  - name: "{{dr_enable_cron_job}}- Replace cron'ed file with App-job-enabled file"
    shell: "cp {{enabled_cron_file}} /var/spool/cron/crontabs/root"
    tags:
      - A39.1

  - name: "{{dr_enable_cron_job}}- Restart cron job"
    shell:
      cmd: ps -ef | grep cron
    register: cmd
    tags:
      - A39.2

  - set_fact:
      pid_2b_delete: "{{ item }}"
    with_items: "{{ cmd.stdout_lines }}"
    when: not item | regex_search('.*' + 'pts' + '.*')
    tags:
      - A39.2

  - set_fact:
      pid_2b_delete: "{{ pid_2b_delete.split()[1] }}"
    tags:
      - A39.2

  - name: "{{ dr_enable_cron_job }}- Killing the process id {{ pid_2b_delete }}"
    shell:
      cmd: "kill -9 {{ pid_2b_delete }}"
    tags:
      - A39.2

  - debug:
      msg: "{{ dr_enable_cron_job }}- cronjob enabled successfully"
    tags:
      - A39.2

  become: yes
  tags:
    - A39
    - B26

