---

- block:
  - debug:
      msg: "{{ dr_update_DB_config }}- Update the Tomcat DB configuration."

  - win_stat:
      path: "{{ win_path }}"
    register: test_file_path

  - fail:
      msg: "{{ dr_update_DB_config }}- tomcat server path {{ win_path }}  doesn't exist."
    when: not test_file_path.stat.exists

  - name: " {{ dr_update_DB_config }}- Check if file exists"
    win_stat:
      path: "{{ mysrc }}"
    register: check_file_name

  - name: "{{ dr_update_DB_config }}- Check if file to be renamed exists"
    debug:
      msg: "File does not exist, hence rename operation not done."
    when: not check_file_name.stat.exists

  - block:
      - name: "{{ dr_update_DB_config }}- Copy existing file to a new file name"
        win_copy:
          remote_src: true
          src: "{{ mysrc }}"
          dest: "{{ mydst }}"
        
      - debug:
          msg: "File name changed."          
    when: check_file_name.stat.exists

  - debug:
      msg: "{{ dr_update_DB_config }}- Updated tomcat DB configuration complete."

  tags:
    - A40
