---

- block:
    - name: "{{ bring_down_App1_App9 }}- URL to check is as follows:"
      set_fact:
        url_2b_verify: 'https://{{inventory_hostname}}:9443/rib'

    - name: "{{ bring_down_App1_App9 }}- Verifying the url {{ url_2b_verify }}"
      uri:
        url: "{{ url_2b_verify }}"
        validate_certs: no
      register: validate_result
      retries: 600
      delay: 3
      failed_when: false
      until: validate_result.status == -1

    - debug:
        var: validate_result

    - name: "{{ bring_down_App1_App9 }}- Report the status of IB Application"
      fail:
        msg: "{{ bring_down_App1_App9 }}- IB Application is up!"
      when: validate_result.status != -1

    - debug:
        msg: "{{ bring_down_App1_App9 }}- IB Application is down!"
      when: validate_result.status == -1
      
  become: yes
  tags:
  - A9a
  - B6a
