---
- block:
    - include_tasks: bring_up_web.yml
      when: inventory_hostname in web_ips
      tags: [A1,A2,A3,A4,A5,A6]

    - include_tasks: bring_down_app.yml
      when: inventory_hostname in app_ips
      tags: [A9,A10,A11,A12,A13,A14,A15,A16,A17]

    - include_tasks: check_App_URL.yml
      when: inventory_hostname in app_ips
      tags: [A9a]

    - include_tasks: stop_ATM_Jompay.yml
      when: inventory_hostname in app_ips
      tags: [A18]

    - include_tasks: stop_CBS_Jompay.yml
      when: inventory_hostname in app_ips
      tags: [A19]

    - include_tasks: disable_cron_job.yml
      when: inventory_hostname in app_ips
      tags: [A20,A20.05,A20.1,A20.2]

    - include_tasks: stop_IB_Report_Quartz.yml
      when: inventory_hostname in app_ips
      tags: [A21]

    - include_tasks: update_db.yml
      vars:
        - tbl_update: "update BANKISLAMMBUAT1.IB_Test set auth_status='A' where content_id='890' and screen_id='DownTime';"
        - update_check: "select auth_status from BANKISLAMMBUAT1.IB_Test where content_id='890' and screen_id='DownTime';"
        - expected_op: "A"
      when: inventory_hostname==prod_db_server_ip
      tags:
       - A22
  become: yes
  
- include_tasks: restart_tomcat_service.yml
  when: inventory_hostname in tomcat_ips
  tags: [A23]

