---
- block:
  - fail:
      msg: "{{ check_uri_act_no }}- {{ url }} is either not defined or is empty"
    when: url is not defined or url|trim==""

  - debug:
      msg: "{{ check_uri_act_no }}- Verifying the url {{ url }}"

  - uri:
      url: "{{ url }}"
      status_code: 200
    ignore_errors: yes

  # ignore the error as certificate is not present. In Prod/DR will remove ignore_errors

  tags:
    - A17
    - B18
