---
- include_tasks: "{{ role_path }}/../pre_activities/tasks/DBSwing.yml"
  vars:
    actNo: "B5"
    dbname: "TBD"
  when: inventory_hostname in dr_gir_db_ips
  tags: [B5]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/mountRecordingStorage.yml" 
  vars:
    actNo: "B7"
    username: "ccgirlinuser"
    password: "nKsr#J9f"
    file_mode: 0777
    dir_mode: 0777
    fileserver: PRDCCFSVR01
    filesystem: "/recording/mnt/recording"
  when: inventory_hostname in webdav_ips
  tags: [B7]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B11"
    svc_name: "{{ item }}"
    action: "stop"
  loop: ["BOEXI40Tomcat","BOEXI40SIAPRDCCADMUI01"]
  when: inventory_hostname in dr_cfg_ips
  tags: [B11]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "B13"
    svc_name: "{{ item }}"
    svc_state: "stopped"
  loop: ["gir", "elasticsearch"]
  when: inventory_hostname in dr_gir_db_ips
  tags: [B13]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "B14"
    svc_name: httpd
    svc_state: "stopped"
  when: inventory_hostname in dr_webdav_ips 
  tags: [B14]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B15"
    svc_name: "IIS Admin Service"
    action: "stop"
  when: inventory_hostname in dr_sm_ips
  tags: [B15]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B16"
    svc_name: "ConfigServer64"
    action: "stop"
  when: inventory_hostname in dr_cfg_ips
  tags: [B16]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B17"
    svc_name: "ConfigServer64"
    action: "start"
  when: inventory_hostname in cfg_ips[0]
  tags: [B17]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B18"
    svc_name: "{{ item }}"
    action: "start"
  loop: ["SCServer64","ConfigServer64_1"]
  when: inventory_hostname in cfg_ips[0]
  tags: [B18]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B18"
    svc_name: "{{ item }}"
    action: "start"
  loop: ["SCServer64","ConfigServer64_1","ConfigServer64"]
  when: inventory_hostname in cfg_ips[1]
  tags: [B18]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B19"
    svc_name: "ConfigServer64_1"
    action: "stop"
  when: inventory_hostname in dr_cfg_ips
  tags: [B19.1]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/editRegistryEntry.yml"
  vars:
    actNo: "B19"
    entryPath: HKLM:\System\CurrentControlSet\Services\ConfigServer64_1
    entryToEdit: ImagePath
    valueToEdit: '"E:\GCTI\Configuration Server\cfgproxy_dr_p" -host PRDCCCR01 -port 2020 -app cfgproxy_dr_p -service ConfigServer64_1 -l 7260@DRCCCR01'
    entryType: expandstring
  when: inventory_hostname in dr_cfg_ips
  tags: [B19.2]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B19"
    svc_name: "ConfigServer64_1"
    action: "start"
  when: inventory_hostname in dr_cfg_ips
  tags: [B19.3]


# Add log
- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkLineExistence.yml"
  vars:
    path: F:\gcti_logs\cfgproxy_dr_p
    line2check: "Port 2080 opened for listening"
  when: inventory_hostname in dr_cfg_ips
  tags: [B19.4]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B20"
    svc_name: "{{ item }}"
    action: "start"
  loop: ["BOEXI40Tomcat","BOEXI40SIAPRDCCADMUI01"]
  when: inventory_hostname in ccm_ips
  tags: [B20]

# wait for the services to start in A21.2
- pause:
    seconds: 10
  tags: always

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkListeningPort.yml"
  vars:
    actNo: "B20"
    hostIp: 127.0.0.1
    portNo: 6400
  when: inventory_hostname in ccm_ips
  tags: [B20]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "B20"
    urlStr: https://localhost:8080/BOE/BI
  when: inventory_hostname in ccm_ips
  tags: [B20]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartWinSvc.yml"
  vars:
    actNo: "B21"
    svc_name: "IIS Admin Service"
    action: "start"
  when: inventory_hostname in ga_ips + sm_ips + tpin_ips
  tags: [B21]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "B21"
    urlStr: "https://localhost/wcm"
  when: inventory_hostname in ga_ips
  tags: [B21]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "B21"
    urlStr: "https://localhost/speechminer"
  when: inventory_hostname in sm_ips[0]
  tags: [B21]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "B21"
    urlStr: "http://172.31.127.200/indexer"
  when: inventory_hostname in sm_ips[1]
  tags: [B21]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkURL.yml"
  vars:
    actNo: "B21"
    urlStr: "http://localhost/8384/CustomerSearch/CustomerSearchWBIC.aspx?nric=<nric>"
  when: inventory_hostname in tpin_ips
  tags: [B21]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/checkAndReplaceLine.yml"
  vars:
    actNo: "B23"
    file: "/Genesys/RWS/Config/application.yaml"
    line2check: "syncNode: \w+"
    line2replace: "syncNode: true"
  when: inventory_hostname in gir_db_ips[0]
  tags: [B23]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "B23"
    svc_name: gir
    svc_state: "started"
  when: inventory_hostname in db_1_ips
  tags: [B23]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "B25"
    svc_name: gir
    svc_state: "restarted"
  when: inventory_hostname in db_1_ips
  tags: [B25]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/runShellCommand.yml"
  vars:
    actNo: "B25"
    cmdStr: >
      "curl -u ops:ops --insecure "
      "https://rwscc.bankislam.com.my:8443/api/v2/ops/genesys-environments/ON_PREMISE_ENVIRONMENT "
      "| python -m json.too"
  when: inventory_hostname in db_1_ips
  tags: [B25]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "B26"
    svc_name: gir
    svc_state: "started"
  when: inventory_hostname in db_2_ips
  tags: [B26]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "B27"
    svc_name: elasticsearch
    svc_state: "started"
  when: inventory_hostname in db_ips + db_2_ips
  tags: [B27]

- include_tasks: "{{ role_path }}/../pre_activities/tasks/stopStartSystemdServices.yml"
  vars:
    actNo: "B28"
    svc_name: httpd
    svc_state: "started"
  when: inventory_hostname in app_webdav_ips
  tags: [B28]
