---
- block:
    - name: "{{ WinService_act_no }} - Check {{service_state}} status"
      win_shell: iisreset /status
      register: service_stat
      become: yes
      become_user: ansible

    - debug:
        var: service_stat

    - set_fact:
        serviceStatus: "{{ service_stat.stdout | regex_findall('^.*Status.*:\\s+(\\w+).*$','\\1') }}"
    
    - set_fact:
        serviceStatusLineCnt: "{{ serviceStatus | length }}"

    - block:
        - debug:
            var: serviceStatus[0]

        - set_fact:
            verifyTrue: true

        - set_fact:
            verifyTrue: false
          when:
            - serviceStatus[0] is defined
            - serviceStatus[0] != 'Runing'
            - serviceStatus[1] is defined
            - serviceStatus[1] != 'Runing'
#          with_items: {0,1,2,3}

        - debug:
            var: verifyTrue

        - debug:
            msg: "{{ WinService_act_no }} - The App services are in running status in {{inventory_hostname}}"
          when:
            - verifyTrue
            - serviceStatusLineCnt|int > 0

        - block:
            - set_fact:
                count: "{{ count|int + 1 }}"
       
            - name: "{{ WinService_act_no }} - Rerun iisreset {{srv_state}}"
              include_tasks: startStopAppSrv.yml
          when: not verifyTrue or serviceStatusLineCnt|int == 0

      when: srv_state == 'start'

    - block:
        - set_fact:
            verifyTrue: true

        - set_fact:
            verifyTrue: false
          when:
            - serviceStatus[item] is defined
            - serviceStatus[item] != 'Stopped'
          with_items: {0,1,2,3}

        - debug:
            msg: "{{ WinService_act_no }} - The App services are stopped in {{inventory_hostname}}"
          when:
            - verifyTrue
            - serviceStatusLineCnt|int > 0

        - block:
            - set_fact:
                count: "{{ count|int + 1 }}"
       
            - name: "{{ WinService_act_no }} - Rerun iisreset {{srv_state}}"
              include_tasks: startStopAppSrv.yml
          when: not verifyTrue or serviceStatusLineCnt|int == 0

      when: srv_state == 'stop'

  tags:
    - A12
    - A4
    - B2
    - B10

