---

- block:
    - debug:
        msg: "{{ DisableScheduler }}- To disable the Scheduler tasks"

    - fail:
        msg: "{{ DisableScheduler }}- Scheduler task list {{ task_names }} doesn't exist."
      when: task_names | length == 0

    - name: "{{ DisableScheduler }} - Disable the Scheduler tasks"
      include_tasks: disableScheduledTask.yml
      vars:
        task_name: "{{ item }}"
      with_items: "{{ task_names }}"
      loop_control:
        loop_var: task_name
  tags:
    - A4a
    - B2a

