  - name: "make lowercase {{ activitylist }}"
    set_fact: 
      activitylist: "{{ activitylist |lower }}"

  - name: "get facts for only selected host target"
    include: "getfacts.yml"
    loop: "{{ activitylist.split(',') }}"
    when: inventory_hostname in steps[activitynumber].targethosts
    loop_control:
      index_var: activityidx
      loop_var: activitynumber 

  - name: "set initial facts for preparation activity"
    set_fact:
      preactivitylist: []

  - name: "set facts for preparation activity"
    set_fact:
      preactivitylist: "{{ preactivitylist + [item] }}"
    loop: "{{ activitylist.split(',') }}"
    when: (item | regex_search('p[0-9]+')) != None

  - name: "set facts for tasks activity"
    set_fact:
      mainactivitylist: "{{ activitylist.split(',') | difference (preactivitylist) }}"

