  # - block:
    - name: "Windows check ports for steps {{ steps[activitynumber].activity }} port: {{ portitem.server }}:{{ portitem.port }}"
      win_wait_for:
        port: "{{ portitem.port }}"
        host: "{{ portitem.server }}"
        timeout: 2
        connect_timeout: 2
      ignore_errors: true
      register: outputport
    - name: "Windows set fact ports for steps {{ steps[activitynumber].activity }}  port: {{ portitem.server }}:{{ portitem.port }}"
      set_fact:
        perportstatus: "{{ portitem.server }}:{{ portitem.port }} -> {{ outputport.msg | default('Port OK') }}" 
    - name: Windows Set stats for port connection check
      set_stats:
        data:
            "step{{activitynumber}}": "{{ inventory_hostname }} to {{ portitem.server }}:{{ portitem.port }} -> {{ perportstatus }}|||||"     
    - name: Windows ports validation status
      set_fact:
        perportstatuslist: "{{ perportstatuslist + [perportstatus] }}"   

    - name: "Windows toggle validation failed for {{ steps[activitynumber].activity }}"
      set_fact:
        validationfailed: true
      when: (perportstatus | regex_search('Port OK')) == None
    # when: ostype == 'windows'


####
