---

ans_password: "@mukmin2020"

ansibleTempDir: "D:\\AnsibleTmp"

ans_control: "10.22.64.88"

conn_test_from_ip: "172.31.126.243"
conn_test_sourceList: "connectivityTest.txt"
conn_test_destList: "D:\\Inetpub\\connectCheck.txt"
conn_test_destDir: "D:\\Inetpub"

checkDirFileSync_priServ: "172.31.126.243"
checkDirFileSync_drServ: "172.31.126.243"
checkDirFileSync_dirLoc: "D:\\Inetpub"

dr_db_ip: "172.31.126.242"
db_ip: "172.31.126.242"

task_names: [
  "Dummy1",
  "Dummy2"
]

prod_app_ips: "UATGWCAPP01.bankislam.com.my"
dr_app_ips: "UATGWCAPP01.bankislam.com.my"

spoolDateServ: "10.22.75.105"

# dr_GWC_Client: [
#   "172.31.122.53",
#   "172.31.122.54",
#   "172.31.122.55",
#   "172.31.122.56"
# ]

# prod_GWC_Client: [
#   "172.31.22.53",
#   "172.31.22.54",
#   "172.31.22.55",
#   "172.31.22.56"
# ]

dr_GWC_Client: [
  "172.31.126.242"
]

prod_GWC_Client: [
  "172.31.126.242"
]

gwc_ip: "172.31.126.242"
