- block:  
  - block:
    - name: 'Unix Ensure file {{ commanditem.filelocation }} content for steps {{ steps[activitynumber].activity }}'
      lineinfile:
        path: "{{ commanditem.filelocation }}"
        regexp: '^auth \\+sufficient \\+pam_radius_auth.so'
        line: "{{ commanditem.filecontent }}"
      become_user: "{{ commanditem.runas }}"
      become: true
    when: commanditem.remediatetype == 'filecontent' 

  - block:
    - name: 'Unix Run command {{ commanditem.command }} for steps {{ steps[activitynumber].activity }}'
      shell: "{{ commanditem.command }}"
      become_user: "{{ commanditem.runas }}"
      become: true
      ignore_errors: true
      register: remediateoutputcommand
    when: commanditem.remediatetype == 'command'
  when: (commandvalidationstatuslist | length == 0) or (commandvalidationstatuslist[commandidx] | regex_search('Command NOT OK') != None)




