- block:
  - block:
    - name: 'Windows Run command {{ commanditem.command }} for steps {{ steps[activitynumber].activity }}'
      ansible.windows.win_powershell:
        script: "{{ commanditem.command }}"
      ignore_errors: true
      register: remediateoutputcommand
    when: commanditem.remediatetype == 'command'

  - block:
    - name: 'Windows copyfile for steps {{ steps[activitynumber].activity }}'
      ansible.windows.win_copy:
        src: "{{ commanditem.src }}"
        dest: "{{ commanditem.dest }}"
      ignore_errors: true
      register: remediateoutputcommand
    when: commanditem.remediatetype == 'copyfile'    
  when: (commandvalidationstatuslist | length == 0) or (commandvalidationstatuslist[commandidx] | regex_search('Command NOT OK') != None)
