---
- hosts: all
  gather_facts: no
  #remote_user: ansible
  tasks:
    - name: Test connection
      ping:
      #remote_user: ansible
...

---

- name: show version
  hosts: telnet
  gather_facts: false
  connection: local
  tasks:
    - name: telnet sw
      telnet:
        command:
          - terminal length 0
          - show version
