---

- block:
    - include_tasks: "{{ role_path }}/../checkpointing-1/tasks/bring_up_app.yml"
      vars:
        bring_up_App01_07: "B14-B23"
      when: inventory_hostname in prod_app_ips
      tags: [B14,B15,B16,B17,B18,B19,B20,B21,B22,B23]

    - include_tasks: "{{ role_path }}/../checkpointing-1/tasks/check_App_URL.yml"
      vars:
        bring_up_App01_07: "B14-B23"
      when: inventory_hostname in prod_app_ips
      tags: [B14a]

    - include_tasks: "{{ role_path }}/../checkpointing-1/tasks/start_ATM_Jompay.yml"
      vars:
        start_ATM_Jompay_Listener: "B24"
      when: inventory_hostname in app_ips
      tags: [B24]

    - include_tasks: "{{ role_path }}/../checkpointing-1/tasks/start_CBS_Jompay.yml"
      vars:
        start_CBS_Jompay: "B25"
      when: inventory_hostname in app_ips
      tags: [B25]

    - include_tasks: "{{ role_path }}/../checkpointing-1/tasks/enable_cronjob.yml"
      vars:
        dr_enable_cron_job: "B26"
      when: inventory_hostname in app_ips
      tags: [B26]

    - include_tasks: start_IB_Report_Quartz.yml
      vars:
        start_IB_Report_Quartz: "B27"
      when: inventory_hostname in app_ips
      tags: [B27]
  become: yes

- include_tasks: "{{ role_path }}/../checkpointing-1/tasks/update_hosts_CDB_server.yml"
  vars:
    Update_host_CDB_Server: "B29"
    CDB_find_line: '^172\.31\.1\.119'
    CDB_line2Replace: '172.31.1.119  nbpsapp'
  when: inventory_hostname in cdb_ips 
  tags: [B29]

- block:
    - include_tasks: "{{ role_path }}/../checkpointing-1/tasks/Update_GO_Mobile_host_file.yml"
      vars:
        update_GO_mobile_host: "B30a"
        find2commentOut: '^172\.31\.123\.89(.*)$'
        line2Replace: '#172.31.123.89 mobilebanking.bankislam.com.my'
        find2uncomment: '^#172\.31\.123\.88(.*)$'
        line2Replace_2: '172.31.123.88 mobilebanking.bankislam.com.my'
      when: inventory_hostname in go_app_ips 
      tags: [B30a]
  become: yes
